In [1]:
import numpy as np
import pandas as pd
def Duplicate_Numbers(munza):
    zinza_gaza = []
    names = (np.array(munza.split()))
    for i in range(len(names)):
        if len(names[i])==10:
            arrr = " ".join(names[i]).split()
            if len(np.unique(arrr)) == 10:
                zinza_gaza.append(True)
            else:
                zinza_gaza.append(False)
        else:
            zinza_gaza.append(False)
    print(zinza_gaza)
                
    
Duplicate_Numbers('0123456789 01234 01234567890 6789012345 012322456789')

[True, False, False, True, False]


In [10]:
import pandas as pd

def Morse_code_Reader(munza2):
    # 모스 부호와 알파벳 대응 관계를 정의
    cord_keys = pd.Series({'A': ".-", 'B': "-...", 'C': "-.-.", 'D': "-..", 'E': ".",
                           'F': "..-.", 'G': "--.", 'H': "....", 'I': "..", 'J': ".---",
                           'K': "-.-", 'L': ".-..", 'M': "--", 'N': "-.", 'O': "---", 'P': ".--.",
                           'Q': "--.-", 'R': ".-.", 'S': "...", 'T': "-", 'U': "..-", 'V': "...-",
                           'W': ".--", 'X': "-..-", 'Y': "-.--", 'Z': "--.."})
    
    # 모스 부호 문자열을 공백을 기준으로 분리
    morse_codes = munza2.split(" ")
    
    # 각 모스 부호를 알파벳으로 변환하여 출력
    for morse_code in morse_codes:
        for key, value in cord_keys.items():
            if value == morse_code:
                print(key, end="")
                break
        else:
            # 모스 부호가 알파벳과 대응되지 않을 경우 " " 출력
            print(" ", end="")

# 모스 부호 문자열을 호출하여 출력
Morse_code_Reader(".... .  ... .-.. . . .--. ...  . .- .-. .-.. -.--")


HE SLEEPS EARLY

In [6]:
import numpy as np

# 1차원 배열 생성
x = np.array([1, 2, 3, 4, 5])

# 배열을 2차원 행렬로 변환 (5x1 행렬)
x_2d = x.reshape(-1, 1)  # 또는 x.reshape(5, 1)

# 배열 슬라이싱을 사용하여도 가능
x_2d_slice = x[:, np.newaxis]  # 또는 x[:, None]

print(x)
print(x_2d)
print(x_2d_slice)

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
