In [ ]:
# 자격증과 산출물 등은 취업어필에 도움이 될 것이다.
# 특히 깃허브에서 산출물 관리를 잘 하는 것이 도움이 될 것이다.
# 산출물을 토대로 논문을 작성해서 학술대회에 작성을 하는 것도 좋다. 컨퍼런스 대회에서 제출하며 논문의 분량은 3~4장가량 된다.
# 논문지도 받고 싶으면 이야기하면 논문작성에 도움을 줄 수 있다.
# 공모전 입상경력은 도움이 된다. 현업에서 가장 어필이 많이 된다. https://dacon.io/


In [5]:
# 넘파이 배열에 대해서 어제에 이어서 진행한다. 어제는 참조하는 것 위주로 시행했다.
import numpy as np
import pandas as pd

In [6]:
x = np.array([1,2,3.0])

In [7]:
x.dtype # 데이터 타입은 실수이다. 플로트

dtype('float64')

In [8]:
y = np.array([1,2,3])
y.dtype # 특별한 것이 없으면 타입은 인트로 나올 것이다. 

dtype('int32')

In [9]:
z = np.array([1,2,3], dtype = 'f')
z.dtype # 사용자가 실수타입으로 정의하는 것도 가능하다.

dtype('float32')

In [10]:
np.array([0,1,-1,0])/ np.array([1,0,0,0])
#출력결과가 나오는 이유를 해설해보면
# inf는 무한대라는 이야기이다. 인피니티의 약자이다. 즉 [제로,무한, -무한, 숫자 없음]으로 출력된 것이다.
# infinity, not a number의 약자들이다.

C:\Users\user\AppData\Local\Temp\ipykernel_11700\4124948042.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0,1,-1,0])/ np.array([1,0,0,0])
C:\Users\user\AppData\Local\Temp\ipykernel_11700\4124948042.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0,1,-1,0])/ np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [11]:
np.linspace(0,100,5)#린스페이스함수는 다음과 같이 쓰는데 0부터 100까지 5구간으로 나누라는 의미이다.

array([  0.,  25.,  50.,  75., 100.])

In [12]:
x

array([1., 2., 3.])

In [13]:
x.T#위와 같은 결과가 나온다.

array([1., 2., 3.])

In [14]:
x2 = np.arange(6).reshape(3,2)
x2 #3행 2열이 나왔다.

array([[0, 1],
       [2, 3],
       [4, 5]])

In [15]:
x2.T# 재밌는 점은 T를 붙이니 행과 열이 바뀌었다.

array([[0, 2, 4],
       [1, 3, 5]])

In [16]:
np.arange(6).reshape(2,-1) # 마이너스는 알아서 결정하라는 의미로 봐도 된다.

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
x2.flatten()#2차원을 1차원으로 바꾸는 평탄화(flatten)작업이다. 

array([0, 1, 2, 3, 4, 5])

In [18]:
x3 = np.arange(24).reshape(2,3,-1)#2개로 나뉘고 3개로 나뉘면서 나머지인 4개가 나누어졌다.
x3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [19]:
x3.flatten()# 다차원을 1차원으로 만드는 것이다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
x3.ravel() # 다차원을 1차원으로 만드는 것으로 플래튼과 비슷하다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
#차원을 감소시키는 것도 되었다면 반대로 차원을 증가시키는 것도 가능하다.
x1 = x2.flatten()
x1

array([0, 1, 2, 3, 4, 5])

In [24]:
x5 = x1.T
x5

array([0, 1, 2, 3, 4, 5])

In [25]:
x1[:,np.newaxis]# 뉴액시스로 차원을 증가시켰다.


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [26]:
a1 = np.ones((2,3))
a1


array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
a2 = np.zeros((2,2))
a2 #행렬 두개를 합치고자 한다면?

array([[0., 0.],
       [0., 0.]])

In [30]:
#스택 함수는 쌓는 함수이다. hvtack(horizon stack수평스택), vstack(vertical stack수직스택)이 있다.
np.hstack([a1,a2]) #옆으로 합쳐지면 이렇게 합쳐졌다.

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [31]:
np.vstack([a1,a2]) # 애러가 발생한다. 열의 갯수가 동일하지 않는데 합치기 시도를 했기 때문이다.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [32]:
b1 = np.zeros((2,3))#열의 갯수를 동일시해보자
b1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.vstack([a1,b1])#열의 갯수가 동일하면 정상적으로 합쳐진다.

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#데이터가 여러개의 파일로 존재하는 경우가 존재한다. 그럴 경우 불러오는 데이터가 여러가개 있는데 이 데이터들을 하나로 합쳐야 할 수도 있다.
#그럴때에 사용된다. 데이터를 쉽게 병합할 수 있다.


In [34]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
c2 = np.zeros((3,4))
c2# 이 행렬들을 3차원 행렬로 구성하기 위해서는? 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
d2 = np.dstack([c1,c2]) # 문제는 마지막 차원에 연결되어 버린다.
d2

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [39]:
d2.shape#새로운 차원은 맨 마지막에 추가가 되었다.
#사실상 뎁스가 3이 되어버린 것이다. 


(3, 4, 2)

In [40]:
#만약 스택을 바로 쓰면 어떨까?
e2 = np.stack([c1,c2])
e2# 차원이 맨 처음에 추가되었다.
# 3행 4열 행렬이 두개가 저장되는 구조가 된 것이다.


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
#엑시스는 기본값이 0이다. 별도로 설정하지 않으면 엑시스(축)은 0으로 결정된다. 즉 내가 원하는 위치의 축을 정하는 것이 가능하다.
e2 = np.stack([c1,c2],axis=0)
e2
# 축은 axis, 축들은 axes로 나타낸다. 

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
f2 = np.stack([c1,c2], axis = 1)
f2# 중간에 축을 추가한 모양이다. 

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [43]:
np.r_[np.array([1,2,3]),np.array([11,12,13])] # r언더바는 옆으로 붙인다.


array([ 1,  2,  3, 11, 12, 13])

In [44]:
np.c_[np.array([1,2,3]),np.array([11,12,13])] # c언더바는 아래로 붙인다.

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [46]:
a = np.array([[0,1],[1,2]])
a # 현재의 배열을 반복하고 싶다면?

array([[0, 1],
       [1, 2]])

In [48]:
np.tile(a,(3,2)) # a를 밑으로 3칸, 옆으로 2칸이 붙었다.

array([[0, 1, 0, 1],
       [1, 2, 1, 2],
       [0, 1, 0, 1],
       [1, 2, 1, 2],
       [0, 1, 0, 1],
       [1, 2, 1, 2]])

In [ ]:
# 이걸 만들고 싶다고 해보자.
array([[   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [   0.,    0.,    0.,    1.,    1.],
       [  10.,   20.,   30.,   40.,   50.],
       [  60.,   70.,   80.,   90.,  100.],
       [ 110.,  120.,  130.,  140.,  150.]])

In [52]:
c = np.linspace(10,150,15).reshape(3,5)
# 밑의 부분을 만든다.

array([[ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [58]:
np.zeros((3,3)) #제로부분을 만든다. 같은 원리로 1부분을 만든다.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.hstack([np.zeros((3,3)),np.ones((3,2))])#둘을 가로로 합친다.

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [56]:
np.vstack([np.hstack([np.zeros((3,3)),np.ones((3,2))]),np.linspace(10,150,15).reshape(3,5)])# 둘을 세로로 합친다.

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [60]:
np.tile(np.vstack([np.hstack([np.zeros((3,3)),np.ones((3,2))]),np.linspace(10,150,15).reshape(3,5)]),(2,1)) 
#이걸 두개를 위아래로 복사해서 이어서 완성한다.

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [62]:
#판다스에는 두 가지 자료구조가 존재한다.
obj = pd.Series([4,3,-2,1])
obj
#시리즈는 1차원으로 자료를 저장할 때 사용한다. 
#리스트를 만들고 시리즈 함수에 전달이 되면 하나의 시리즈가 만들어진다.
# 0123순으로 적힌 숫자는 행 인덱스이다. 
#아직은 열 인덱스는 없다. 

0    4
1    3
2   -2
3    1
dtype: int64

In [63]:
type(obj) #타입은 판다스 코어 시리즈라고 나온다. 약칭 시리즈이다. 1차원 구조가 특징이다.

pandas.core.series.Series

In [64]:
obj.array # 판다스 어레이로 출력되었다.

<PandasArray>
[4, 3, -2, 1]
Length: 4, dtype: int64

In [65]:
obj.index # 레인지 인덱스가 출력되었다. 0번부터 3번까지 있으며 1씩 증가한다는 뜻이다.

RangeIndex(start=0, stop=4, step=1)

In [66]:
obj2 = pd.Series([4,3,-2,1], index=['d','b','a','c'])
obj2 # 인덱스 순서가 0123에서 dbac로 바뀌었다.


d    4
b    3
a   -2
c    1
dtype: int64

In [67]:
obj2.index #레인지 인덱스가 아니다. 그냥 인덱스로 나왔다. 인덱스의 타입이 오브젝트라는 뜻이다.


Index(['d', 'b', 'a', 'c'], dtype='object')

In [68]:
obj2['b'] #마치 딕셔너리처럼 직접참조도 가능하다.

3

In [69]:
obj2['b'] = 10
obj2 # 딕셔너리처럼 특정 데이터를 변경하는 것도 가능하다.

d     4
b    10
a    -2
c     1
dtype: int64

In [70]:
obj2['b','c','a']
#다만 참조는 1개씩만 가능하다. 여러개를 참고하고 싶다면 리스트로 묶어야 한다.

KeyError: 'key of type tuple not found and not a MultiIndex'

In [71]:
obj2[['b','c','a']]
#즉 bca를 새로운 리스트로 만들어서 출력시킨 것이다. 여러개를 한번에 참조할 때는 이렇게 하면 된다.


b    10
c     1
a    -2
dtype: int64

In [72]:
#만약 양수만 추출하고자 하면
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [73]:
#불린 참조로 한다면
obj2[obj2 > 0]
#불린 참조는 매우 많이 사용된다. 그리고 파이썬에는 저런 문법이 존재하지 않기에 햇갈릴 수 있다.

d     4
b    10
c     1
dtype: int64

In [74]:
obj2

d     4
b    10
a    -2
c     1
dtype: int64

In [75]:
obj2*2 #각각의 요소에 대해서 두배가 되었다. 넘파이 array랑 동일하다.

d     8
b    20
a    -4
c     2
dtype: int64

In [76]:
'b' in obj2 # 단순하게 참조할 수 있다. 불 형식으로 답장이 온다.

True

In [77]:
'k' in obj2 # 없는 경우 다음과 같이 출력된다.

False

In [78]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata) #딕셔너리로부터 시리즈를 만들었다. 시리즈는 딕셔너리로부터 만드는 것도 가능하다. 
# 딕셔너리를 시리즈로 바끄면 키는 인덱스로 변한다. 그리고 데이터타입이 하단에 출력된다.
# 숫자는 경단위로 바뀌는 순간 오브젝트로 바뀌게 된다.920경까지는 int64였다가 920경이 넘는 순간 요브젝트가 된다.
# 오브젝트는 문자타입니다. 파이썬의 str이 아닌 obj인것이다. obj는 문자다.
# 또는 실수타입(float타입)으로 변환하는 것도 방법이다. 대부분의 숫자들이 구현 가능하다. int64보다 범위가 더 넓다.
# 즉 표현범위는 int32< int64< float32< float64 인 것이다.
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [79]:
obj3.to_dict()# 기존의 시리즈에서 딕셔너리로 바꾸는 법니다.

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [80]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4 # 하이인덱스는 직접 줄 수 있다. 직접 준 값으로 시리즈를 만들었는데. 캘리포니아는 존재하지 않아서 NaN으로 나왔다.
#nan이 존재하면 모든 자료는 자동으로 float로 바뀐다. ISN


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [84]:
# 그래서 자료를 제작할 때는 항상 계측값의 유무를 확인해야한다.
pd.isna(obj4) # is함수로는 내부에 NAN값이 나오는지 확인 가능하다. 자주 쓰인다.

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [85]:
obj3 +  obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [ ]:
# NaN하고 더하면 결과가 nan가 나온다.
# 어느 한쪽에만 인덱스가 있고 어느 한쪽에만 없는 경우 여지없이 nan이 나온다.
# 양쪽 모두에 있는 경우 더해서 출력한다.

In [86]:
obj4 # 만약 오하요주의 값을 출력한다면

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [88]:
obj4['Ohio'] # 딕셔너리랑 비슷하다.

35000.0

In [89]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [90]:
s2 = pd.Series([9904312, 3448737, 2890451, 2466052])
s2# 인덱스를 지정하지 않았기에 자동적으로 0번부터 일련번호가 붙었다.

0    9904312
1    3448737
2    2890451
3    2466052
dtype: int64

In [91]:
pd.Series(range(11,15))#리스트와 딕셔너리 말고도 레인지도 출력이 되는 것을 알 수 있다.

0    11
1    12
2    13
3    14
dtype: int64

In [93]:
s.index # 인덱스만 출력되었다.

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [94]:
s.values # 벨류만 출력되었다.

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [98]:
s.name = "인구" #이름을 부여해보자.

In [99]:
 # 이름이 붙은 것을 볼 수 있다. 별도로 붙이는 경우는 흔치는 않음

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [100]:
s /1000000# 시리즈에 대해 연산을 하게 되면 시리즈 내부의 구성성분에 대해 동일하게 연산이 이루어진다.

서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

In [102]:
s['부산']

3448737

In [103]:
s[1] # 인덱스가 저장되어있는 번호가 적혀있어도 값이 출력되는 것을 볼 수 있다.
# 번호는 0번부터 존재한다는 것은 파이썬과 같다.

3448737

In [107]:
#출력순서를 바꾸고자 한다면?
#서울 대구 부산순서대로 출력해보도록 한다면
s[[0,3,1]] # 아까 배운대로 대괄호를 두개를 씌워야 한다. 여러개 참조할때는 대괄호 두개다.

서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [108]:
s


서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [117]:
# 조건을 주는 방식으로 해보자. 250만 이상. 500만 이하로 해보자. 불린참조를 써보자.
#2500000 <=s 
s < 5000000
# 두 개의 조건을 둘다 만족하려면?
(s>=2500000) & (s <5000000)# 앤드를 써서 붙이도록 하자.

서울    False
부산     True
인천     True
대구    False
Name: 인구, dtype: bool

In [118]:
s[(s>=2500000) & (s <5000000)] #이처럼 부산과 인천만 출력되었다. 이러한 용법은 굉장히 많이 쓰인다.

부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [121]:
s[:]#콜론기호는 전체출력이다.

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [122]:
s[1:]#1번 행 인덱스부터 마지막까지 출력한다.

부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [123]:
s[:2]#0번과 1번을 출력했다.

서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [124]:
s[1:3]#1번과 2번을 출력했다.

부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [126]:
s['부산':"대구"] #인덱스 이름을 주는 것도 가능하다. 근데 이번것은 마지막 번호까지 포함했다.숫자 인덱스와 차이가 이것이다.

부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [ ]:
# 시리즈에서 행 단위로 데이터를 추출할때는 인덱스 이름이나 행 인덱스 번호를 주면 된다.
# 일정한 범위 내의 데이터를 추출하고자 할 때에는 행에 대한 번호로 범위를 참조할 수 있고 행 이름을 직접 기재하여 참조가 가능하다.
# 이름으로 직접 기재할 경우 이름까지 전체 참조한다.

In [127]:
s.부산 # 한글의 경우에도 정상적으로 값이 출력이 되었다. 

3448737

In [129]:
"인천" in s # 묻는 것도 가능하다.

True

In [130]:
"강릉" in s 

False

In [132]:
#인덱스와 데이터를 구분해서 읽고싶은 경우도 있을 것이다. 
s.items() # 이런 식으로 압축을 먼저 한다.

In [133]:
for k,v in s.items(): #k와 v에 저장하였다.
    print(k)
    print(v)

서울
9904312
부산
3448737
인천
2890451
대구
2466052


In [134]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [136]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천","대전"])
s2 # 인덱스가 추가되면 기존에 적혀있는 순서는 무시되고 인덱스 순으로 출력된다.

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [137]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천","대전","광주"])
s2 # 광주에 대한 키가 존재하나 데이터가 존재하지 않아서 NAN이 출력되었다.


부산    3393191.0
서울    9631482.0
인천    2632035.0
대전    1490158.0
광주          NaN
dtype: float64

In [138]:
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [139]:
s2

부산    3393191.0
서울    9631482.0
인천    2632035.0
대전    1490158.0
광주          NaN
dtype: float64

In [141]:
ds = s-s2 # 데이터가 어느 한쪽에만 있는 경우 산술결과가 nan이 나온다.
ds

광주         NaN
대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [144]:
ds.isna() # 사용할 수 없는 데이터인가? 데이터가 있냐 없냐의 차이이다. 


광주     True
대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [145]:
ds.isnull() #값이 없는가? 아까랑 결과가 같다.

광주     True
대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [146]:
ds.notnull() # 아까와 정 반대의 질문이다.

광주    False
대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [147]:
ds[ds.notnull()] # null이 아닌 자료들만 찾아서 출력하기

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [148]:
ds[ds >= 200000] # ds에서 20만 이상의 자료만 추출해보았다.

서울    272830.0
인천    258416.0
dtype: float64

In [149]:
ds.부산 = 50000

In [151]:
ds['속초'] = 100000

In [152]:
ds # 데이터를 변경하는 방법과 데이터를 추가하는 방법은 동일하다.

광주         NaN
대구         NaN
대전         NaN
부산     50000.0
서울    272830.0
인천    258416.0
속초    100000.0
dtype: float64

In [153]:
del ds["대구"]

In [154]:
ds

광주         NaN
대전         NaN
부산     50000.0
서울    272830.0
인천    258416.0
속초    100000.0
dtype: float64

In [156]:
# 배열에서 연산을 하는 법에 대해서 알아보자.
x = np.arange(1,100)
y = np.arange(10001,10100)#각각 99개씩 존재할 것이다.
print(x);print(y)
#시리즈가 아니다. 배열array이다.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[10001 10002 10003 10004 10005 10006 10007 10008 10009 10010 10011 10012
 10013 10014 10015 10016 10017 10018 10019 10020 10021 10022 10023 10024
 10025 10026 10027 10028 10029 10030 10031 10032 10033 10034 10035 10036
 10037 10038 10039 10040 10041 10042 10043 10044 10045 10046 10047 10048
 10049 10050 10051 10052 10053 10054 10055 10056 10057 10058 10059 10060
 10061 10062 10063 10064 10065 10066 10067 10068 10069 10070 10071 10072
 10073 10074 10075 10076 10077 10078 10079 10080 10081 10082 10083 10084
 10085 10086 10087 10088 10089 10090 10091 10092 10093 10094 10095 10096
 10097 10098 10099]


In [158]:
print(x+y) # 파이썬은 리스트끼리 합치려면 for문을 써야하지만 넘파이에서는 배열끼리 수식을 한번에 연산하게 된다.
# 이를 벡터연산이라고 한다. C언어로 구성이 되어있어서 빠른 연산이 가능하다.

[10002 10004 10006 10008 10010 10012 10014 10016 10018 10020 10022 10024
 10026 10028 10030 10032 10034 10036 10038 10040 10042 10044 10046 10048
 10050 10052 10054 10056 10058 10060 10062 10064 10066 10068 10070 10072
 10074 10076 10078 10080 10082 10084 10086 10088 10090 10092 10094 10096
 10098 10100 10102 10104 10106 10108 10110 10112 10114 10116 10118 10120
 10122 10124 10126 10128 10130 10132 10134 10136 10138 10140 10142 10144
 10146 10148 10150 10152 10154 10156 10158 10160 10162 10164 10166 10168
 10170 10172 10174 10176 10178 10180 10182 10184 10186 10188 10190 10192
 10194 10196 10198]


In [159]:
print(x>y) # for문을 쓸 필요 없이 각각 사용하게 된다. 

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False]


In [160]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [161]:
#3개의 배열에 대해서 연산을 해보자.
a == b
#연산자 하나로 비교연산이 수행되어버렸다.

array([False,  True, False,  True])

In [162]:
c[a == b] #a와 b가 같은 위치의 c의 값을 출력하라는 뜻이다. true에 해당하는 것을 참조한다는 것이다.


array([2, 4])

In [163]:
a==c # 요소끼리 일치하는 것을 말한다.

array([ True,  True,  True,  True])

In [164]:
np.all(a==c) #모든 값이 일치하는가?

True

In [165]:
np.any(a==b) #하나라도 일치하는가?

True

In [167]:
a = np.array([1, 2, 3, 4])
np.sum(a)#더하는 것은 쉽게 이루어진다.


10

In [168]:
a.sum()#배열쓰고 함수써도 동일하다.

10

In [169]:
print(a.max())#최댓값이 나온다.
print(a.min())#최솟값이 나온다.


4
1


In [173]:
print(a.argmax())#최대값이 저장된 위치값(키)이 출력된다. argument의 약자다.
print(a.argmin())#최소값이 저장된 위치값(키)이 출력된다.


3
0


In [177]:
a = np.array([1,2,8,9,10])

In [178]:
print(a.mean()) #평균 출력 

6.0


In [179]:
print(np.median(a)) #중위수 출력. 평균과 중위수는 중심경향치를 파악하는데 사용한다.
# 평균은 어느 한쪽에 치우쳐저 있거나 극단적인 값이 많이 존재하는 경우에 왜곡이 될 수 있다.
# 전체 데이터를 대표하는 대표값을 알고자 할 때 전체 데이터에 중심위치의 경향을 알고싶을때 사용한다.
# 왜곡이 되는지를 확인하고 싶다면 데이터화를 해서 그래프로 그리면 된다.
# 왜곡이 많이 발생하면 중위수를 흔히 쓴다. 극단적인 값에 대해서 중간값을 구하면 되기 때문이다.
# 최빈수가 존재한다. 최대 빈도수로 등장한 수를 말한다. 데이터의 중심경향치로 참고할 수 있다.

8.0


In [180]:
# 편차(deviation)는 관측값에서 평균 또는 중앙값을 뺀 것이다.
# 앞으로 자주 사용할 개념이다.

In [181]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [184]:
a.sort() # 하나의 행을 기준하여 열 방향으로 이동하여 정렬하였다. 즉 열 단위로 정렬했다.
a # 엑시스(행)이 다르면 정렬은 따로따로 진행된다.

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [193]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [192]:
a.sort(axis = 0) #재밌는 것은 위아래단위로 정렬이 되었다.아까는 좌에서 우로 정렬되었지만 엑시스가 0이면 위에서 아래로 정렬된다.
a

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [194]:
#만약 내림차순으로 정렬한다면 a에 대해 reverse를 하면 될 것이다.


In [195]:
a = np.array([42, 38, 12, 25])  
np.argsort(a) # 오름차순 정렬 시 해당 인덱스의 위치를 나타낸다. 
#아그소트는 자주 쓰인다. 

array([2, 3, 1, 0], dtype=int64)

In [196]:
a[np.argsort(a)] # 그래서 이것을 그대로 집어넣으면 결과가 그대로 나오게 된다.

array([12, 25, 38, 42])

In [198]:
a[np.argsort(a)][::-1] # reverse는 쉽게 하자.

array([42, 38, 25, 12])

In [200]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
len(x)

26

In [201]:
#일반적으로 평균을 구하는 것은 이렇게 해왔다.
print(x.sum()/len(x))
print(x.mean()) #이제는 새로운 방법도 쓰자.
print(np.mean(x)) #매우 간단하게 할 수 있다.

4.8076923076923075
4.8076923076923075
4.8076923076923075


In [202]:
# 분산은 데이터가 평균 인근에 얼마나 흩어져있는지를 나타내는 정도이다.
# 분산의 정의는 각각의 데이터가 얼마나 평균에 떨어져있는지 보여주는 것이다. .
# 각각의 데이터에서 평균을 뺀다(편차) 데이터가 평균보다 크면 양수, 작으면 음수가 나온다.
# 각 데이터-평균을 제곱해서 음수부호를 먼저 없앤 상태에서 전부 더한다. 1/n(sum((data-mean)**2))으로 나타낸다. 
# 이것을 모분산이라고 한다. 전체 데이터에 대한 분산이다. 데이터의 갯수가 n개니까.

In [203]:
# 표본분산은 다르다. 1/n(sum((data-mean)**2))로 정의한다. 
# 표준편차는 분산의 제곱근이다. 분산에 루트를 씌운 것이다. 
# co variance는 공분산이다. 변수가 한개가 아니라 두개가 있는 경우의 분산을 말한다.
.


In [204]:
# (합(데이터 - 평균))/데이터 갯수 이대로 하면 마이너스 데이터로 인해 데이터가 오염된다.
# (합(데이터 - 평균)제곱)/데이터 갯수로 계산을 하는 것이 일반적이다.


In [208]:
# 상관분석
# 부모님의 키와 자식의 키 사이에 관계가 있을까?와 같은 질문의 대답에 필요하다.
# 즉 상관성이 있는지 없는지를 알고싶을때 사용한다.
# 부모님의 키의 변화에 따른 자식키의 변화하는 정도를 알 수 있다면 부모님키와 자식키간의 상관관계를 분석할 수 있다.
'''
                                           ^ 자녀키
2사분면                                    |                                                      1사분면
              부모키는 작은데              |
             자녀키는 더 크다.             |
             (음의 상관관계)               |
                                           |                부모키, 자녀키가 둘다 크다.(양의 상관관계)
                                           |
                                           |
------------------------------------------------------------------------------------------------------>
                                           |                                                        부모님 키
                                           |
    부모키가 작고 자녀키도 작다.           |
     (양의 상관관계)                       |
                                           |               부모키가 큰데 자녀키가 작다.
                                           |               (음의 상관관계)
3사분면                                    |                                                      4사분면
'''
print()
# 만약 모든 사분면에 동일하게 위치한다면 뭐라고 하기 딱 말할 수 없다. 
# 그 이전에 위에 데이터만을 가지고 판단하기 어렵다.
# 다만 데이터가 중앙에서 멀리 떨어질 수록 특성을 더 강력하게 가지고 있다고 말할 수 있다.
# 그렇기에 면적을 구해서 더하자는 것이다. 공분산은 그렇게 만들어지는 것이다.
# 더 멀리 떨어져 있는 데이터는 더 강한 영향을 발휘한다고 본다. 
# 현재 키를 기준으로 계산하는데 센티미터로 이루어지는 경우와 미터단위로 이루어지는 경우가 단위차이가 크게 난다.
# 공분산 값은 단위에 따라 달라지기에 단위를 통일할 필요가 있다. 기준이 되는 단위를 정하는 것을 표준화 라고 한다.


In [209]:
# 상관분석을 반드시 해야한다. 엄청나게 많은 정보(가족력, 혈액형, 신장, 무게, 발병여부)들을 가지고 조사한다.
# 변수들을 전부 쓸 수 있어도 의미없는 변수를 쓸 필요는 없다. 관련이 없는 것은 소거해야 한다.
# 당뇨병 발병에 영향을 주는 중요한 요소들을 종합해야 하는데 그 상관관계를 조사하는데 공분산을 쓴다.
# 상관계수가 큰 것을 기준으로 상관분석을 하면 좋은 분석결과가 나온다는 것이다.
# 예측모델을 만들때 중요하지 않는 변수를 사용하지 않기 위해. 좋은 변수를 최대한 끌어내기 위해. 상관분석이 반드시 필요하다.
# 상관분석도 상당히 여러 종류가 존재한다. 
# 평균을 구할 수 있어야 하고 분산을 구할 수 있어야 한다. 

In [210]:
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [212]:
np.var(x) #분산을 출력한다.

115.23224852071006

In [216]:
np.sum((x-np.mean(x))**2)/len(x) # 분산을 구하는 공식이다.

115.23224852071006

In [217]:
np.std(x) # 이것이 표준편차이다.


10.734628476137871

In [218]:
np.sqrt(np.sum((x-np.mean(x))**2)/len(x))#편차를 sqrt로 씌우면 표준편차를 구할 수 있다.

10.734628476137871

In [220]:
np.percentile(x,0) # 제일 작은 값이다. 0퍼센트 지점이다.

-24.0

In [221]:
np.percentile(x,25) # 1사분위수. 25퍼센트 지점이다.


0.0

In [222]:
np.percentile(x,50) # 2사분위수. 50퍼센트 지점이다.

5.0

In [223]:
np.percentile(x,75) # 3사분위수. 75퍼센트 지점이다.

10.0

In [224]:
np.percentile(x,100) # 4사분위수. 100퍼센트 지점이다.

23.0