In [1]:
# 소득 훈련파일 호출
import numpy as np
import pandas as pd

soduk = pd.read_csv('train.csv')
soduk   

ID  Age Gender                Education_Status  \
0      TRAIN_00000   63      M                    Middle (7-8)   
1      TRAIN_00001   37      M  Associates degree (Vocational)   
2      TRAIN_00002   58      F                   High graduate   
3      TRAIN_00003   44      M                   High graduate   
4      TRAIN_00004   37      F                   High graduate   
...            ...  ...    ...                             ...   
19995  TRAIN_19995   33      M                   High graduate   
19996  TRAIN_19996   20      F                         College   
19997  TRAIN_19997   22      M                         College   
19998  TRAIN_19998   76      F                   High graduate   
19999  TRAIN_19999   41      F                   High graduate   

              Employment_Status  Working_Week (Yearly)  \
0                     Full-Time                      4   
1                     Full-Time                     52   
2                     Full-Time                     52   
3                     Full-Time                     52   
4                     Full-Time                     52   
...                         ...                    ...   
19995  Children or Armed Forces                     52   
19996                 Full-Time                     12   
19997  Children or Armed Forces                     52   
19998               Not Working                      0   
19999  Children or Armed Forces                     52   

                   Industry_Status                 Occupation_Status   Race  \
0                  Social Services                          Services  White   
1                    Entertainment                          Services  White   
2      Manufacturing (Non-durable)  Admin Support (include Clerical)  Black   
3                           Retail             Technicians & Support  White   
4                           Retail                             Sales  White   
...                            ...                               ...    ...   
19995      Manufacturing (Durable)                 Handlers/Cleaners  White   
19996                    Education  Admin Support (include Clerical)  White   
19997               Transportation             Technicians & Support  White   
19998  Not in universe or children                           Unknown  White   
19999        Public Administration  Admin Support (include Clerical)  White   

         Hispanic_Origin  ... Citizenship Birth_Country  \
0              All other  ...      Native            US   
1              All other  ...      Native            US   
2              All other  ...      Native            US   
3              All other  ...      Native            US   
4              All other  ...      Native            US   
...                  ...  ...         ...           ...   
19995          All other  ...      Native            US   
19996   Mexican-American  ...      Native            US   
19997          All other  ...      Native            US   
19998          All other  ...      Native            US   
19999          All other  ...      Native            US   

      Birth_Country (Father) Birth_Country (Mother)  \
0                         US                     US   
1                         US                     US   
2                         US                     US   
3                         US                     US   
4                         US                     US   
...                      ...                    ...   
19995                     US                     US   
19996                 Mexico                 Mexico   
19997                     US                     US   
19998               Scotland                England   
19999                     US                     US   

                                        Tax_Status Gains Losses Dividends  \
0                                         Nonfiler     0      0         0   
1                                           Single   

In [2]:
soduk.info()
# 1. 아이디는 드랍한다. 단지 순서만을 나타내며 소득과는 연관이 없다. 
# 2. 나이는 남겨둘 것이다. 이것은 매우 중요한 정보이다. 하지만 카테고리화가 필요할
# 것이다. 여기서 아이(~18), 청년(18-35), 중년(36-65), 노년 순으로 정리하자. 
# 3. 성별 또한 카테고리가 적으면서 매우 중요하다. 
# 4. 학력은 카테고리화가 반드시 필요하다. 학교 카테고리화는 반드시 진행할 것이다. 
# 5. 고용상태에 따른 분류도 매우 중요하다. 그대로 사용한다.
# 6. 주 노동량은 53개의 카테고리로 존재한다. 4 단위로 카테고리화 시킬 예정이다.
# 7. 산업고용분포의 4688과 직업상태의 4688은 동일하다. 여기에 주목하자. Unknown을 
# 먼저 Not in universe or children 로 대체하자. 어쩌면 직업상태가 카테고리가 더 적어서
# 쓸만해보인다.
# 8. 인종은 매우 중요한 지표다. 
# 9. 히스패닉여부는 좀 더 지켜보자. 미국에는 히스패닉이 많기에 어디출신인지까지
# 신경쓸지는 미지수이다. 
# 10. 결혼은 매우 주요하다. 
# 11. 가구구성은 간략화 구성을 사용한다. 우리는 마약탐지를 하는게 아니다. 
# 12. 시민권은 당연히 중요하다. 
# 13. 출신국가는 대륙별로 분류하자. 너무 복잡해진다.
# 14. 세금보고서도 중요하다.
# 15. Gains, Losses도 중요성이 있을지라도 다른 요소들보다 중요하다고 생각되지 않는다.
# 16. 배당이 소득과 상관없다고 해도 연관성분석은 필요할 것이다. 
# 17. 소득수준은 중요하다.
# 18. 답안지인 소득은 최종제출은 5단위로 분류해서 제출하도록 계획하자

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   ID                      20000 non-null  object
 1   Age                     20000 non-null  int64 
 2   Gender                  20000 non-null  object
 3   Education_Status        20000 non-null  object
 4   Employment_Status       20000 non-null  object
 5   Working_Week (Yearly)   20000 non-null  int64 
 6   Industry_Status         20000 non-null  object
 7   Occupation_Status       20000 non-null  object
 8   Race                    20000 non-null  object
 9   Hispanic_Origin         20000 non-null  object
 10  Martial_Status          20000 non-null  object
 11  Household_Status        20000 non-null  object
 12  Household_Summary       20000 non-null  object
 13  Citizenship             20000 non-null  object
 14  Birth_Country           20000 non-null  object
 15  Bi

In [3]:
# 1. ID열 제거
soduk.drop('ID', axis=1 ,inplace = True)

In [4]:
# 2. 나이 카테고리화
# 나는 나이를 4 단위로 분류할 것이다.
soduk['Age']

0        63
1        37
2        58
3        44
4        37
         ..
19995    33
19996    20
19997    22
19998    76
19999    41
Name: Age, Length: 20000, dtype: int64

In [5]:
def classify_age(age):
    if age <= 17:
        return 'Child'
    elif 18 <= age <= 35:
        return 'Youth'
    elif 36 <= age <= 65:
        return 'Middle'
    else:
        return 'Silver'
soduk['Age_Category'] = soduk['Age'].apply(classify_age)

soduk['Age_Category']
    

0        Middle
1        Middle
2        Middle
3        Middle
4        Middle
          ...  
19995     Youth
19996     Youth
19997     Youth
19998    Silver
19999    Middle
Name: Age_Category, Length: 20000, dtype: object

In [6]:
# 3. 성별은 그냥 둔다. 그대로도 원핫 인코딩에 활용 가능하다. 
# 4. 학력은 축약한다. 옆에 있는 숫자는 걸리적거린다. 
soduk['Education_Status']


0                          Middle (7-8)
1        Associates degree (Vocational)
2                         High graduate
3                         High graduate
4                         High graduate
                      ...              
19995                     High graduate
19996                           College
19997                           College
19998                     High graduate
19999                     High graduate
Name: Education_Status, Length: 20000, dtype: object

In [7]:
def Education(edu):
    if  edu == "High Freshman" or edu == "High Junior" or edu == "High Sophomore" or edu == "High Senior":
        return 'High'
    elif edu == "Elementary (5-6)" or edu == "Elementary (1-4)":
        return 'Elementary'
    elif edu == 'Middle (7-8)':
        return 'Middle'
    else:
        return edu
soduk['Education_Category'] = soduk['Education_Status'].apply(Education)

soduk['Education_Category']

0                                Middle
1        Associates degree (Vocational)
2                         High graduate
3                         High graduate
4                         High graduate
                      ...              
19995                     High graduate
19996                           College
19997                           College
19998                     High graduate
19999                     High graduate
Name: Education_Category, Length: 20000, dtype: object

In [8]:
soduk['Education_Category'].value_counts()

Education_Category
High graduate                     6494
College                           3794
High                              2416
Children                          2208
Bachelors degree                  1956
Associates degree (Vocational)     741
Associates degree (Academic)       609
Middle                             548
Masters degree                     505
Elementary                         467
Professional degree                111
Doctorate degree                    87
Kindergarten                        64
Name: count, dtype: int64

In [9]:
def classify_working_week(weeks):
    if weeks == 0:
        return 'Not_Working'
    elif 1 <= weeks <= 13:
        return 'Part-Time'
    elif 14 <= weeks <= 26:
        return 'Semi-Full-Time'
    else:
        return 'Full-Time'

soduk['Working_Category'] = soduk['Working_Week (Yearly)'].apply(classify_working_week)
soduk['Working_Category']
# 시간이 0부터 52까지 너무 많다. 이걸 4개의 카테고리로 나눠보자. 

0          Part-Time
1          Full-Time
2          Full-Time
3          Full-Time
4          Full-Time
            ...     
19995      Full-Time
19996      Part-Time
19997      Full-Time
19998    Not_Working
19999      Full-Time
Name: Working_Category, Length: 20000, dtype: object

In [10]:
# 먼저 스택을 이용해서 Not in universe or children이 정마로 unknown과 일치하는지 확인하자. 
# 우연의 일치일 가능성도 있기 때문이다.
stack = 0
search = soduk['Industry_Status'] 
find = soduk['Occupation_Status'] 
for i in range(len(search)):
    if search[i] == 'Not in universe or children':
        if find[i] =='Unknown':
            stack+=1
print(stack)
# 결과값은 4688이다. 즉 Not in universe or children과 Unknown은 일치하는 항목이다. 

4688


In [11]:
# 인종은 그대로 사용한다. 
# 히스패닉은 이번에 사용하지 않는다. 추후 사용할 경우 Hispanic으로 일괄 전환시킨 다음 인종에 끼워넣을 것이다. 

In [12]:
# 결혼 자료는 그대로 쓸 것이다. 가구구성 간략화만 사용할 것이다. 
# 시민권은 그냥 둘 것이다. 그 자체로 유용하다.

In [13]:
# 출생지는 중요하다. 미국과 대륙을 나눠야 한다. 
def classify_country(country):
    if country == 'US' or country == 'Outlying-U S (Guam USVI etc)':
        return 'US'
    elif country in ['Mexico', 'Puerto-Rico', 'Cuba', 'Dominican-Republic', 'El-Salvador', 'Guatemala', 'Honduras', 'Nicaragua', 'Panama']:
        return 'North_America'
    elif country in ['Columbia', 'Ecuador', 'Peru']:
        return 'South_America'
    elif country in ['Philippines', 'India', 'South Korea', 'Vietnam', 'Japan', 'China', 'Taiwan', 'Hong Kong', 'Cambodia', 'Laos', 'Thailand']:
        return 'Asia'
    elif country in ['Germany', 'Canada', 'England', 'Poland', 'Italy', 'Portugal', 'Ireland', 'France', 'Greece', 'Scotland', 'Yugoslavia', 'Hungary', 'Holand-Netherlands']:
        return 'Europe'
    else:
        return 'Unknown'

# 새로운 카테고리 열 추가
soduk['Birth_Country_Category'] = soduk['Birth_Country'].apply(classify_country)
# 아프리카와 오세아니아 출신 사람들은 아마 Unknown에 있을 것이다. 


In [14]:
# 세금보고서는 그대로 쓸 것이야. 그리고 Gains와 Losses는 쓰지 않을것이다. 
# 분석에서 제외될 변수: "ID", "Gains", "Losses", "Dividends"
# 분석에 포함될 주요 변수: "Age", "Gender", "Education_Status", 
# "Employment_Status", "Working_Week (Yearly)", "Race", "Martial_Status", 
# "Household_Summary", "Citizenship", "Birth_Country" (대륙별로 분류), 
# "Tax_Status", "Income_Status"


In [15]:
soduk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Age                     20000 non-null  int64 
 1   Gender                  20000 non-null  object
 2   Education_Status        20000 non-null  object
 3   Employment_Status       20000 non-null  object
 4   Working_Week (Yearly)   20000 non-null  int64 
 5   Industry_Status         20000 non-null  object
 6   Occupation_Status       20000 non-null  object
 7   Race                    20000 non-null  object
 8   Hispanic_Origin         20000 non-null  object
 9   Martial_Status          20000 non-null  object
 10  Household_Status        20000 non-null  object
 11  Household_Summary       20000 non-null  object
 12  Citizenship             20000 non-null  object
 13  Birth_Country           20000 non-null  object
 14  Birth_Country (Father)  20000 non-null  object
 15  Bi

In [16]:
# 다음과 같이 가공하자.
# 'Age_Category' : 원핫 인코딩으로 가공
# "Gender" : 원핫 인코딩으로 가공
# 'Education_Category' : 원핫 인코딩으로 가공
# 'Working_Category' : 원핫 인코딩으로 가공
# 'Occupation_Status' : 원핫 인코딩으로 가공
# "Race" : 원핫 인코딩으로 가공
# "Martial_Status" : 원핫 인코딩으로 가공
# "Household_Summary" : 원핫 인코딩
# "Citizenship" : 원핫 인코딩
# "Birth_Country_Category" : 원핫 인코딩
# "Tax_Status" : 원핫 인코딩
# "Income_Status" : 원핫 인코딩
# 원-핫 인코딩을 적용할 열만 선택
columns_to_encode = [
    'Age_Category', 'Gender', 'Education_Category', 'Working_Category', 
    'Occupation_Status', 'Race', 'Martial_Status', 'Household_Summary', 
    'Citizenship', 'Birth_Country_Category', 'Tax_Status', 'Income_Status'
]

# 지정된 열에 대해서만 원-핫 인코딩 적용
soduk_encoded = pd.get_dummies(soduk, columns=columns_to_encode)

In [17]:
print(soduk_encoded.head())

   Age                Education_Status Employment_Status  \
0   63                    Middle (7-8)         Full-Time   
1   37  Associates degree (Vocational)         Full-Time   
2   58                   High graduate         Full-Time   
3   44                   High graduate         Full-Time   
4   37                   High graduate         Full-Time   

   Working_Week (Yearly)              Industry_Status Hispanic_Origin  \
0                      4              Social Services       All other   
1                     52                Entertainment       All other   
2                     52  Manufacturing (Non-durable)       All other   
3                     52                       Retail       All other   
4                     52                       Retail       All other   

        Household_Status Birth_Country Birth_Country (Father)  \
0            Householder            US                     US   
1  Nonfamily householder            US                     US   
2    

In [18]:
soduk_encoded.info()
# 여기서 필요없는 열을 드랍하자. 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 92 columns):
 #   Column                                                               Non-Null Count  Dtype 
---  ------                                                               --------------  ----- 
 0   Age                                                                  20000 non-null  int64 
 1   Education_Status                                                     20000 non-null  object
 2   Employment_Status                                                    20000 non-null  object
 3   Working_Week (Yearly)                                                20000 non-null  int64 
 4   Industry_Status                                                      20000 non-null  object
 5   Hispanic_Origin                                                      20000 non-null  object
 6   Household_Status                                                     20000 non-null  object
 7   Birth_Country

In [19]:
# 드랍열 설정
columns_to_drop = [
    "Age", "Education_Status", "Employment_Status", "Working_Week (Yearly)", 
    "Industry_Status", "Hispanic_Origin", "Household_Status", 
    "Birth_Country", "Birth_Country (Father)", "Birth_Country (Mother)", 
    "Gains", "Losses", "Dividends"
]

# 지정된 열들을 드랍
soduk_encoded_dropped = soduk_encoded.drop(columns=columns_to_drop)

# 드랍된 이후의 데이터프레임 확인
soduk_encoded_dropped

# 이렇게 전처리를 완료하게 되었다. income부분은 답지에 해당된다. 
# 답지를 제외하면 모두 

Income  Age_Category_Child  Age_Category_Middle  Age_Category_Silver  \
0         425               False                 True                False   
1           0               False                 True                False   
2         860               False                 True                False   
3         850               False                 True                False   
4         570               False                 True                False   
...       ...                 ...                  ...                  ...   
19995    1300               False                False                False   
19996     850               False                False                False   
19997     999               False                False                False   
19998       0               False                False                 True   
19999     671               False                 True                False   

       Age_Category_Youth  Gender_F  Gender_M  \
0                   False     False      True   
1                   False     False      True   
2                   False      True     False   
3                   False     False      True   
4                   False      True     False   
...                   ...       ...       ...   
19995                True     False      True   
19996                True      True     False   
19997                True     False      True   
19998               False      True     False   
19999               False      True     False   

       Education_Category_Associates degree (Academic)  \
0                                                False   
1                                                False   
2                                                False   
3                                                False   
4                                                False   
...                                                ...   
19995                                            False   
19996                                            False   
19997                                            False   
19998                                            False   
19999                                            False   

       Education_Category_Associates degree (Vocational)  \
0                                                  False   
1                                                   True   
2                                                  False   
3                                                  False   
4                                                  False   
...                                                  ...   
19995                                              False   
19996                                              False   
19997                                              False   
19998                                              False   
19999                                              False   

       Education_Category_Bachelors degree  ...  \
0                                    False  ...   
1                                    False  ...   
2                                    False  ...   
3                                    False  ...   
4                                    False  ...   
...                                    ...  ...   
19995                                False  ...   
19996                                False  ...   
19997                                False  ...   
19998                                False  ...   
19999                                False  ...   

       Birth_Country_Category_Unknown  Tax_Status_Head of Household (HOH)  \
0                               False                               False   
1                               False                               False   
2                               False                               False   
3                               False                               False   
4                               False                

In [20]:
# 이제 훈련데이터와 테스트 데이터를 나눠보자.
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest=train_test_split(        # 트레인데이터, 테스트데이터 분리결과
    soduk_encoded_dropped.drop(['Income'],axis=1),soduk_encoded_dropped.Income,        # 정답 데이터 드롭한것이 트레인, 정답 데이터는 답지
    test_size=0.2,random_state= 41)                   # 테스트용으로는 20%만 사용, 랜덤값은 41로 고정

In [22]:
# 로지스틱으로 해보자. 
from sklearn.linear_model import LogisticRegression # 사이킷런 리니어모델 - 로지스틱 회귀
clf = LogisticRegression()                          # 로지스틱회귀모델 제작
clf.fit(xtrain,ytrain)                              # 모델링 절차 - 회귀모델 제작
ans = clf.predict(xtest)                                  # 테스트 문제풀이
ans

C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of it

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 성능 평가
print("Accuracy:", accuracy_score(ytest, ans))
print("Confusion Matrix:\n", confusion_matrix(ytest, ans))
print("Classification Report:\n", classification_report(ytest, ans))
# 정확도가 고작 42%밖에 안된다. 어쩔 수 없다. 소득은 범위기 때문에 정확하게 보는건 어렵다. 

Accuracy: 0.42675
Confusion Matrix:
 [[1684    0    0 ...    0    0    0]
 [   3    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   3    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]
 [   1    0    0 ...    0    0    0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.44      0.98      0.61      1714
         100       0.00      0.00      0.00         3
         143       0.00      0.00      0.00         1
         150       0.00      0.00      0.00         1
         200       0.50      0.25      0.33         4
         210       0.00      0.00      0.00         1
         212       0.00      0.00      0.00         1
         213       0.00      0.00      0.00         6
         225       0.00      0.00      0.00         1
         233       0.00      0.00      0.00         1
         250       0.00      0.00      0.00         5
         255       0.00      0.00      0.00         1
        

C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_d

In [25]:
# 선형회귀는 다음과 같이 진행한다. 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# 특성과 타겟 변수를 준비합니다.
X = soduk_encoded_dropped.drop(['Income'], axis=1) # 타겟 변수를 제외한 특성만 사용
y = soduk_encoded_dropped['Income'] # 타겟 변수

# 데이터를 훈련 세트와 테스트 세트로 나눕니다.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=41)

# 선형 회귀 모델 객체를 생성합니다.
model = LinearRegression()

# 훈련 데이터를 사용하여 모델을 학습시킵니다.
model.fit(X_train, y_train)

# 테스트 데이터에 대한 예측을 수행합니다.
y_pred = model.predict(X_test)

# 성능 평가: 여기서는 평균 제곱 오차(MSE)와 결정 계수(R^2)를 사용합니다.
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("평균 제곱 오차(MSE):", mse)
print("결정 계수(R^2):", r2)

평균 제곱 오차(MSE): 430958.393
결정 계수(R^2): 0.22898259403836718


C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  i

In [26]:
# 랜덤 포레스트로 확인하기
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# 랜덤 포레스트 회귀 모델 객체를 생성합니다.
# n_estimators는 결정 트리의 수를 의미합니다. 여기서는 예시로 100개의 트리를 사용합니다.
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# 훈련 데이터를 사용하여 모델을 학습시킵니다.
rf.fit(X_train, y_train)

# 테스트 데이터에 대한 예측을 수행합니다.
y_pred_rf = rf.predict(X_test)

# 성능 평가
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("랜덤 포레스트 회귀의 평균 제곱 오차(MSE):", mse_rf)
print("랜덤 포레스트 회귀의 결정 계수(R^2):", r2_rf)

# 결정계수가 22에서 13으로 하락했다. 아까보다 더 안좋다.

C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


랜덤 포레스트 회귀의 평균 제곱 오차(MSE): 483354.927853507
랜덤 포레스트 회귀의 결정 계수(R^2): 0.13524120034394338


C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  i

In [27]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score

# 그래디언트 부스팅 회귀 모델 객체를 생성합니다.
gbr = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1,
                                max_depth=3, random_state=42)

# 훈련 데이터를 사용하여 모델을 학습시킵니다.
gbr.fit(X_train, y_train)

# 테스트 데이터에 대한 예측을 수행합니다.
y_pred_gbr = gbr.predict(X_test)

# 성능 평가
mse_gbr = mean_squared_error(y_test, y_pred_gbr)
r2_gbr = r2_score(y_test, y_pred_gbr)

print("그래디언트 부스팅 회귀의 평균 제곱 오차(MSE):", mse_gbr)
print("그래디언트 부스팅 회귀의 결정 계수(R^2):", r2_gbr)
# 좀더 나아졌다. 24정도면 괜찮아졌다. 

C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


그래디언트 부스팅 회귀의 평균 제곱 오차(MSE): 424412.3186704467
그래디언트 부스팅 회귀의 결정 계수(R^2): 0.24069401985298


C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\elcco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  i