In [89]:
#문제풀이 순서를 정해보자.
# 문제에 쓰일 재료를 준비하자.
gravity=[7,4,2,0,0,6,0,7,0]
# 0으로 이루어진 리스트를 만들어보자.
matrix = [[0 for _ in range(9)] for _ in range(8)]

# 리스트를 출력해보자
for row in matrix:
    print(row)
    
# 좌표출력은 다음과 같이 이루어진다.
print(f"좌표 ({x}, {y}): {matrix[x][y]}")

# 그래비티의 값만큼 매트릭스의 값을 증가시켜보자.
for i in range(len(gravity)):
    num_stack = gravity[i]
    while num_stack > 0:
        matrix[-num_stack][i] = 1
        num_stack -= 1
for row in matrix:
    print(row)
# 그림과 같이 숫자가 채워졌다. g2에서 주어진 그림과 같다.




    

[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
좌표 (2, 3): 0
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 0, 0, 0, 1, 0]
[1, 0, 0, 0, 0, 1, 0, 1, 0]
[1, 0, 0, 0, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 0, 1, 0, 1, 0]
[1, 1, 0, 0, 0, 1, 0, 1, 0]
[1, 1, 1, 0, 0, 1, 0, 1, 0]
[1, 1, 1, 0, 0, 1, 0, 1, 0]


In [90]:
# 이제 문제를 풀기 위해서 상자를 오른쪽으로 붙이는 시도를 해보자.
for k in range(-1,-9,-1):
    for l in range(-1,-10,-1):
        if matrix[k][l] == 0:
            print(f"{k}{l}")
# 맨 아래 구석부터 왼쪽으로 가는 것을 볼 수 있다. 이것을 이용할 것이다.

-1-1
-1-3
-1-5
-1-6
-2-1
-2-3
-2-5
-2-6
-3-1
-3-3
-3-5
-3-6
-3-7
-4-1
-4-3
-4-5
-4-6
-4-7
-5-1
-5-3
-5-5
-5-6
-5-7
-5-8
-6-1
-6-3
-6-5
-6-6
-6-7
-6-8
-7-1
-7-3
-7-4
-7-5
-7-6
-7-7
-7-8
-8-1
-8-2
-8-3
-8-4
-8-5
-8-6
-8-7
-8-8
-8-9


In [91]:
ans_list = []
for k in range(-1, -9, -1):
    move_stack = 0
    for l in range(-1, -10, -1):
        if matrix[k][l] == 0:
            move_stack += 1
        elif matrix[k][l] == 1:
            matrix[k][l] = 0
            matrix[k][l + move_stack] = 1
            ans_list.append(move_stack)
# 리스트를 출력해보자
for row in matrix:
    print(row)         
# 자. 한쪽으로 몰린 것을 볼 수 있을것이다. 
# 내부에 무브스택을 기재해서 1이 움직인 값을 기록한다.
max_value = max(ans_list)
# 무브스택이 기록된 리스트 내부에서 최댓값을 구한다.
print(max_value)
# 이런 식으로 최댓값을 구해서 답을 찾는게 가능하다.


[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1, 1]
[0, 0, 0, 0, 0, 0, 1, 1, 1]
[0, 0, 0, 0, 0, 0, 1, 1, 1]
[0, 0, 0, 0, 0, 1, 1, 1, 1]
[0, 0, 0, 0, 0, 1, 1, 1, 1]
[0, 0, 0, 0, 1, 1, 1, 1, 1]
[0, 0, 0, 0, 1, 1, 1, 1, 1]
7


In [82]:
gravity=[7,4,2,0,0,6,0,7,0]
gravity.reverse()
num=max(gravity)
list1=[]

for i in gravity:
    if i==0:
        list1.append([str(i)*max(gravity)])
    else:
        list1.append([("1"*i)+("0"*(num-i))])
        list1
#----------------------
column_sums = [0] * len(list1[0][0])
for row in list1:
    for i, digit in enumerate(row[0]):
        column_sums[i] += int(digit)
# 결과 출력
for column_sum in column_sums:
    print(9-column_sum)

4
4
5
5
6
6
7


In [83]:
import numpy as np

def nakcha():
    lis = list(map(int, list(input())))

    Tetris = np.zeros((len(lis),len(lis)))

    n=0
    for i in lis:
        Tetris[:i,n] = n+1
        n+=1

    non_zero_count_list = []
    for i in range(0,len(lis)):
        selected_row = Tetris[i,:]
        non_zero_count = np.count_nonzero(selected_row)
        non_zero_count_list.append(non_zero_count)
    

    min_Tetris = np.argmin(non_zero_count_list)
    min_Tetris
    
    final = Tetris[min_Tetris,:]

    final_min = np.argmin(final)
    final_min

    print("정답은",lis[final_min-1],"입니다")

nakcha()

[7,4,2,0,0,6,0,7,0]


ValueError: invalid literal for int() with base 10: '['

In [84]:
array=[[1,1,1,0,0,1,0,1,0],[1,1,1,0,0,1,0,1,0],[1,1,0,0,0,1,0,1,0],
       [1,1,0,0,0,1,0,1,0],[1,0,0,0,0,1,0,1,0],[1,0,0,0,0,1,0,1,0],[1,0,0,0,0,0,0,1,0]]

count_zero=[]          #0의 갯수가 낙차를 의미
for i in range(len(array)):
    count_zero.append(array[i].count(0))
    

max(count_zero)     #0의 갯수 중 최대값

7

In [95]:
import numpy as np
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(arr)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]


In [97]:
print(arr.T)

[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]


In [98]:
print(np.dot(arr,arr.T))

[[ 1  2  3  0  0]
 [ 2  9  8  1 -1]
 [ 3  8 49 -8  8]
 [ 0  1 -8  2 -2]
 [ 0 -1  8 -2  2]]


In [99]:
print(arr@ arr.T)#이것이 왜 곱해지는 것인지 모르겠습니다.

[[ 1  2  3  0  0]
 [ 2  9  8  1 -1]
 [ 3  8 49 -8  8]
 [ 0  1 -8  2 -2]
 [ 0 -1  8 -2  2]]


In [104]:
print(np.random.randint(1,11,6)) # 난수를 뽑아내기

[10  7 10  9  9  4]


In [109]:
print(np.random.randint(1, 11, size=(3,2))) # 랜덤한 수를 뽑아내기

[[ 8  3]
 [10 10]
 [ 4  7]]


In [113]:
arr2 = np.random.randint(1, 11, size=(3,2))
print(arr@ arr2)
print(arr)
print(arr2)

[[ 6  9]
 [15  9]
 [50 43]
 [-6 -6]
 [ 6  6]]
[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
[[5 1]
 [6 9]
 [1 5]]


In [ ]:
# 벡터에 대해서
# 날짜에 따라 장부를 작성한다고 하자. 사과, 배, 딸기, 바나나 순으로 판매된 수량을 적어놓았다.
(5,2,1,0)
(0,1,2,3)
...
(2,3,1,0)
# 여기서 사과, 배, 딸기, 바나나의 가격을 기준하였다.
# 사과 = 200, 배 = 100 , 딸기 = 300, 바나나 = 500
# 여기서 자료를 읽는 순서를 행렬이라고 한다.
# 행 벡터, 열 백터로 나누는 것이다.
# 방금 있던 행렬의 곱셈을 한다면 다음과 같다.
(5,2,1,0)  사과   200  
(0,1,2,3)  배     100
...        딸기   300
(2,3,1,0)  바나나 500
#만약 1일치를 곱한다면 5*200+ 2*100 + 1*300 + 0*500 = 1500
#이런식으로 작성이 되는 것이다.


In [ ]:
arr3 = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
arr4 = np.array([[100],[200],[500]])
print(arr3 @ arr4)
#곱은 이런 식으로 이루어진다.

In [154]:
# 만약 위의 사례같은 케이스로 기준하자면
machul = np.array([[5,2,1,0],[0,1,2,3],[2,3,1,0]])
gaguak = np.array([[200],[100],[300],[500]])
print(machul@gaguak)
# 하루의 매출을 이렇게 정리를 할 수 있게 되었다.
# 곱셈의 원리는 이렇게 이루어지는 것이다. 

[[1500]
 [2200]
 [1000]]


In [ ]:
# 영상처리에서도 자주 사용된다. 
# 사람얼굴 이미지가 흑백 이미지는 1개의 채널이 있다. 
# 0부터 255까지 출력하는 것은 컬러 이미지로 나오게 된다.
# 이미지도 결국 행렬이다. 이미지로부터 자료도 이런 행렬로 바뀐다.
# 색을 변화시키는 것도 결국 저 내부의 숫자를 바꾼 결과물이다.
# 줌인 줌아웃, 이미지 변환, 회전 등 전부 행렬에 대해서 연산한 결과이다.
# 특히 이미지 처리 쪽에서 행렬연산을 많이한다.

In [ ]:
# 정규분포는 종 모양으로 대칭을 이루는 데이터모양이다.
# 중간값을 기준으로 종모양처럼 튀어나와있다는 것이다.
# 평균을 디폴트값으로 지정하고(대체로 0) 표준편차를 1로 정의한 분포를 "표준정규분포"라고 한다.
# 표준정규분포로부터 난수를 발생시키는 함수를 두고 스탠다드 노멀이라고 한다.
# 표준정규분포로부터 데이터를 추출하는 것이다.


In [117]:
samples = np.random.standard_normal(size=(4,4))
print(samples)

[[ 0.58013993  0.81716738 -1.54767469  1.0818598 ]
 [-0.17508613 -0.4501625   0.79115164 -0.87969175]
 [ 0.73420238 -1.17876216  0.26712432 -0.40431998]
 [-1.01920977 -0.4679291   0.07751787  0.92354151]]


In [118]:
np.mean(samples) #샘플의 의미는 무엇인가?

-0.05313320327527734

In [119]:
np.std(samples) #1에 가깝게 수렴한다. 

0.8076973329869945

In [122]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [128]:
print((xarr * cond) + (yarr * ~cond)) # 덧셈을 하면 요소끼리 덧셈을 해버린다. 
#즉 트루면 곱한것에 폴스만 곱한것을 더하는 식이다.

[1.1 2.2 1.3 1.4 2.5]


In [130]:
print([(x if c else y)for x, y ,c in zip(xarr, yarr, cond)])

[1.1, 2.2, 1.3, 1.4, 2.5]


In [132]:
np.where(True,"참","거짓")#조건에 대한 수행 결과는 첫번째 칸, 참일때는 두번째, 거짓일 때는 세번째칸에 대입이 가능하다.
print(np.where(cond,xarr,yarr)) #엔피웨어는 잘 쓰면 굉장히 편하다. 

[1.1 2.2 1.3 1.4 2.5]


In [141]:
np.where(arr<0,0,arr)#np.where를 이런 식으로 사용한다. 

array([[1.08566414, 0.        , 0.        , 0.01241491],
       [0.08875437, 0.        , 0.        , 0.08406801],
       [0.        , 0.        , 0.        , 0.11059884],
       [0.        , 0.82750095, 0.        , 0.41213991]])

In [146]:
import pandas as pd
import numpy as np

lst_A = {'제품':['milk','juice','bread','icecream'],
         '수량':[3,5,10,2],
         '제조일시':['2020-01-01 01:00:00','2019-12-20 15:01:00','2019-12-31 00:00:00','2020-01-02 02:03:01']}

df = pd.DataFrame(lst_A)

df['제조일시'] = pd.to_datetime(df['제조일시'])
df
df['제조일시'] = pd.to_datetime(df["제조일시"])
df

제품  수량                제조일시
0      milk   3 2020-01-01 01:00:00
1     juice   5 2019-12-20 15:01:00
2     bread  10 2019-12-31 00:00:00
3  icecream   2 2020-01-02 02:03:01

In [150]:
#수량이 5 미만이면 적정으로, 그렇지 않으면 초과로 문자열을 초과여부 면에 추가하고 싶다. 
#수량이 5 미만일 때 초과여부를 열에 저장하고 싶다면? 넘파이의  where함수를 이용해서 풀 수 있따.
df['초과여부'] = np.where(df['수량']<5, "적정", "초과")
df
#np.where는 다양한 연산, 작업, 출력을 수행할 수 있게 해 준다.


제품  수량                제조일시 초과여부
0      milk   3 2020-01-01 01:00:00   적정
1     juice   5 2019-12-20 15:01:00   초과
2     bread  10 2019-12-31 00:00:00   초과
3  icecream   2 2020-01-02 02:03:01   적정

In [151]:
#만약 제품종류 열을 추가하고 싶다고 하자. 제품 열 값이 'juice' -> 음료라는 텍스트를 넣고 아니면 간식으로 추가해보자.
df['제품종류'] = np.where((df['제품']=='juice')|(df['제품']=='milk'), '음료','간식')
df

제품  수량                제조일시 초과여부 제품종류
0      milk   3 2020-01-01 01:00:00   적정   음료
1     juice   5 2019-12-20 15:01:00   초과   음료
2     bread  10 2019-12-31 00:00:00   초과   간식
3  icecream   2 2020-01-02 02:03:01   적정   간식

In [ ]:
# 인공지능을 잘하기 위해서는 어떤 것을 해야하는가? 사실 다 잘해야 한다.
# 인공지능은 분량과 관계가 없다. 잘하는 것이 많을 수록 좋다. 관심이 있으면 더 좋다. 
# 농업, 어업, 광업 등 특정 분야에 대해서 분석을 하게 되면 전문가가 아니더라도 찾아보고 알아보게 되어있다.
# 분석결과를 보고 분석결과를 해석하는 능력도 중요하다.

In [158]:
print(arr) #아까 사용한 난수모음을 가져와보았다.
print(arr.mean()) # 평균이 나올 것이다.
print(np.mean(arr)) # 같은 평균이 나올것이다.
print(np.sum(arr)) # 내부 더하기도 다음과 같다.
print(arr.sum()) # 방법은 동일하다.

[[ 1.08566414 -0.02259017 -2.08907487  0.01241491]
 [ 0.08875437 -0.67075695 -0.19629262  0.08406801]
 [-0.43162076 -1.6082035  -2.1775646   0.11059884]
 [-2.19352672  0.82750095 -0.82481705  0.41213991]]
-0.4745816321219424
-0.4745816321219424
-7.593306113951078
-7.593306113951078


In [160]:
arr = np.arange(10,15)
print(arr.cumsum())#누적합. 점점 하나씩 더해간다.

array([10, 21, 33, 46, 60])

In [162]:
arr = np.arange(10,16).reshape(3,2)
print(arr)#3행 2열로 재정렬

[[10 11]
 [12 13]
 [14 15]]


In [164]:
arr.cumsum(axis=0) #열단위로 누적합이 구해진다.

array([[10, 11],
       [22, 24],
       [36, 39]])

In [165]:
arr.cumsum(axis=1) #행단위로 누적합이 구해진다.

array([[10, 21],
       [12, 25],
       [14, 29]])

In [167]:
# 파이썬과 넘파이의 리스트는 전혀 다르다.
a = [[10,11],[12,13],[14,15]]
#만약 파이썬에서 전부 더한다면 for문을 돌려야 하는 번거로움이 존재한다.
stack_num = 0
for i in a:
    for j in i:
        stack_num += j
print(stack_num)

75


In [169]:
#근데 넘파이는 이게 너무 쉽게 된다.
print(arr.sum())

75


In [171]:
#만약 13 이상의 값을 출력한다고 한다면? 
stack_num = 0
for i in a:
    for j in i:
        if j>=13:
            stack_num += j
print(stack_num)

42


In [181]:
# 넘파이에서는 더 쉽다.
print(arr>13) # 리스트 내에서 바로 일치여부 확인이 가능하다.
print(arr)
print(arr[arr>=13].sum()) # 매우 간단하다. 한줄로 처리되었다.


[[False False]
 [False False]
 [ True  True]]
[[10 11]
 [12 13]
 [14 15]]
75
42


In [184]:
print(arr[0])
print(arr[1])
print(arr[2])
# 행을 순서대로 출력하면 이렇게 된다. 만약 다른 방식대로 출력해보면?


[10 11]
[12 13]
[14 15]


In [185]:
print(arr[1,0,2])#파이썬 문법대로 한다면 오류가 발생한다.

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [187]:
print(arr[[1,0,2]])#신기한건 대괄호를 두번 씌우면 잘 된다.
brr = arr[[1,0,2]]
brr.sort(axis=0)
print(brr)#신기한 것은 sort를 쓰면 열 단위로 오름차순으로 정렬되었다. 
brr.sort(axis=1) # 이러면 행 단위로 오름차순으로 정렬되었다.


[[12 13]
 [10 11]
 [14 15]]
[[10 11]
 [12 13]
 [14 15]]


In [190]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
#데이터가 중복된 경우가 존재한다. 중복 데이터를 제거하는 법을 알아보자
print(np.unique(names)) # 중복 데이터를 사라지게 했다. 마치 세트와 비슷하다.

['Bob' 'Joe' 'Will']


In [199]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints)) # 숫자도 세트마냥 중복데이터를 삭제했다.

[1 2 3 4]


In [198]:
print(set(names)) #유니크는 세트처럼 중복을 제거한다. 하지만 세트는 자료구조가 세트이며 유니크는 array자료구조이다.
# 세트는 위치값이 존재하지 않는다. 하지만 array는 자료 위치가 존재한다!

{'Bob', 'Will', 'Joe'}


In [200]:
np.random.rand(3)#0에서 1까지의 난수가 3개가 나올것이다.
#재밌는 것은 랜덤환 난수를 동기화시키는 법이 존재한다! 


array([0.93298435, 0.19528376, 0.29197328])

In [202]:
np.random.seed(20230907)
np.random.rand(3) # 다른 컴퓨터와 동일하게 난수가 발생할 것이다. 시드가 같은 숫자여야만 동일한 난수가 발생한다.
#그리고 난수는 고정되었다.

array([0.64824332, 0.27289441, 0.9663242 ])

In [209]:
x= np.arange(10)
print(x)
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[5 3 1 8 6 9 7 2 0 4]


In [210]:
np.random.seed(20230907)
np.random.shuffle(x)
print(x)

[1 9 8 6 3 5 7 0 2 4]


In [223]:
np.random.seed(20230907)

In [224]:
np.random.shuffle(x)

In [225]:
x

array([3, 9, 7, 4, 5, 1, 0, 2, 8, 6])

In [226]:
np.random.choice(5) # 0부터 4까지 나오게 된다.

1

In [227]:
np.random.choice(5, 3) # 0부터 4까지 3개가 나오게 된다.
#랜덤하게 추출될 때 동일하게 추출될 수 있다.

array([0, 4, 0])

In [228]:
np.random.choice(5, 3, replace=False) # 0부터 4까지 중복되지 않는 3개의 수가 나온다.

array([4, 3, 2])

In [229]:
np.random.choice(5, 10, replace=False) # 0부터 4까지 주고 10개를 추출하라고 하면 당연히 애러가 난다.

ValueError: Cannot take a larger sample than population when 'replace=False'

In [231]:
print(np.random.choice(46,6,replace=False))

[39 37 12 22 10 33]
