In [ ]:
# 파이썬 데이터 분석은 개인적으로 공부하는 것을 추천한다. 
# 책에 있는것보다 훨씬 더 많이 다뤄야 하기 때문에 개인공부가 필요하다.
# 프로젝트를 주제를 정하고 해야 한다. 
# 패키지는 넘파이, 판다스를 공부하고 맷플랍립, 플랏리, 태블로, 씨본 등 시각화 도구를 사용할 것이다.
# 넘파이 공부 = 배열 프로그래밍을 공부한다 


In [ ]:
# 배열 프로그래밍이란 대량의 데이터를 빠르게 연산하는 과정이다. 많은 숫자 데이터를 관리하고 저장할 경우 속도가 많이 느려진다.
# 기존에 사용되는 파이썬 리스트는 속도가 느리고 메모리 차지비중이 매우 높다. 
# 넘파이(수치연산 패키지) 배열은 속도가 더 빠르고 메모리를 덜 차지한다. 그렇기에 넘파이 배열을 이용한다. 파이썬 리스트와 비슷하기도 하고..
# 넘파이 배열의 유일한 단점은 넘파이는 원소의 갯수가 변경되지 않는다는 것이다.
# 파이썬은 자체적으로 배열을 제공하지 않는다. 파이썬에서 배열을 쓰고 싶을 경우 넘파이를 사용해야한다.
# 일반적으로 선형대수 연산을 수행한다.(벡터, 행렬 등) 내부적으로 C 언어로 구현되어져 있다. 구문도 간단하다.


In [3]:
import numpy as np
ar = np.array([1.1,2,3]) # array(배열)로 저장되었다. 점은 플롯이다. 점을 붙이는 순간 다른 타입도 점이 생기는 것을 볼 수 있다.
print(ar)
print(type(ar))

[1.1 2.  3. ]
<class 'numpy.ndarray'>


In [13]:
myarr = np.arange(10)
mylist = list(np.arange(10))
print(mylist)
print(np.arange(10))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [15]:
%timeit myarr2 = myarr*2
%timeit mylist2=[x*2 for x in mylist]
#연산할 때 속도가 매우 차이가 많이 난다.

714 ns ± 7.82 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
735 ns ± 5.73 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
%timeit myarr3 = myarr*2
%timeit mylist3=[x*2 for x in mylist]

720 ns ± 6.04 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
733 ns ± 9.61 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
#넘파이가 빠른 이유는 수행하는 문장의 차이로 인함이다.
# 평소에는 넘파이 쓰자. 그 다음에 필요할 때만 리스트를 이용하는 것이 유용하다.


In [101]:
data = np.array([[1.0, -0.1, 2.0],
                 [0.0, -3.0, 6.0]])
print(data)

[[ 1.  -0.1  2. ]
 [ 0.  -3.   6. ]]


In [103]:
data = data.tolist()  # NumPy 배열을 리스트로 변환
result = list(data + data)  # 리스트를 두 번 사용

print(result)

[[1.0, -0.1, 2.0], [0.0, -3.0, 6.0], [1.0, -0.1, 2.0], [0.0, -3.0, 6.0]]


In [105]:
arr=np.array([1,2,3])
print(arr.ndim)# 넘파이 차원수. 현재것은 1이 반환된다.
print(arr.dtype) # 데이터 타입. int32 가 반환됨
print(arr*3+1) # 각 배열에 3을 곱하고 1을 더하라!


1
int32
[ 4  7 10]


In [ ]:
([1,2,3])


In [3]:
array540 == 2
array(False == False, True)

NameError: name 'array540' is not defined

(arr == 2) (|arr>2)

In [108]:
print(type(arr))
#출력결과는 numpy.ndarray 타입인 것을 확인할 수 있다.


<class 'numpy.ndarray'>


In [35]:
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.ones((3,2)))
print(np.ones((3,2))*2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]
 [2. 2.]]


In [37]:
#초기화는 0이나 1로 하는 경우가 많다.
# 만약 다른 숫자로 하고싶다면 1로 설정하고 원하는 값을 곱하자.
print(arr)

[1 2 3]


In [47]:
arr2 = np.ones(3)
print(arr2)
print(arr+arr2)
print(arr*arr2)
#같은 위치의 요소끼리 연산이 된다.
arr1 = arr.astype(np.float64)#타입변환 명령어이다. 플롯으로 변화시키는 것으로 arr1.astype(float)도 가능하다.
print(arr1)
print(arr1.dtype)
arr1 = arr.astype(np.int32)
print(arr1) 
#이런 식으로 타입변화가 가능하다.

[1. 1. 1.]
[2. 3. 4.]
[1. 2. 3.]
[1. 2. 3.]
float64
[1 2 3]


In [48]:
print(arr > arr2)#요소간 연산이 이루어졌다.

[False  True  True]


In [109]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
arr[5:8] = 100
print(arr)#567이 한번에 100이 되었다. 일괄적으로 특정영역의 값을 변환하는 것이 가능하다.
# 비슷한 원리로 따로 저장도 가능하다
hund = arr[5:8]
print(hund)
arr[1] = 999
print(arr)
#특정값, 특정위치, 특정범위 바꾸는 것, 저장하는 것 다 가능하다
arr= np.arange(10)
arr[:]=10#일괄적으로 변환시키는 방법이다.
print(arr)


[  0   1   2   3   4 100 100 100   8   9]
[100 100 100]
[  0 999   2   3   4 100 100 100   8   9]
[10 10 10 10 10 10 10 10 10 10]


In [57]:
arr2d = np.arange(1,10).reshape(3,3)#reshape를 이용하여 리스트 3개의 형식으로 변경하였다.
print(arr2d[1][1]) #행렬 구성값을 이렇게 만들어보았다.
print(arr2d[1,2])#사실 같이 지정해도 무난하다.


5
6


In [61]:
#1~12까지 값으로 3행 4열을 만들고 데이터 10을 참조한다면?
arr2d2 = np.arange(1,13).reshape(3,4)
print(arr2d2[2,1])
print(len(arr2d2))
print(len(arr2d2[0]))

10
3
4


In [65]:
d = np.arange(1, 25).reshape(2,3,4)
print(d) # 이것을 3차원 배열이라고 한다. 깊이, 행 열 순으로 배열되기 때문이다.
len(d)#차원이 먼저 출력이 되었다.
len(d[0]) #행의 갯수가 출력되었다.
len(d[0][0]) # 열의 갯수가 출력되었다.
print(d.ndim)#3차원
print(d.shape)#배열 구성은?
#3차원 배열 참조방법
# 3차원은 축이 상당히 중요하다. 

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3
(2, 3, 4)


In [71]:
print(np.sum(arr))#전체합계
print(np.sum(arr,axis=0))

100
100


In [76]:
print(np.sum(d)) #전체합계는 300이다. 점 하나로 압축하였다.
print(np.sum(d,axis = 0))# 차원. 축을 기준으로 합계를 구하였다. 연산 이후 차원이 감소되었다.(2,3,4)에서 2가 사라졌다.
print(np.sum(d,axis = 1))# n차원에서 차원끼리 합을 하게 되면 n-1차원으로 감소한다. 현재는 행을 기준으로 합계가 이루어졌다.(2,3,4)에서 3이 사라졌다. 
print(np.sum(d,axis = 2))# 열을 기준으로 합이 이루어졌다. (2,3,4)에서 4가 사라졌다.


300
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
[[15 18 21 24]
 [51 54 57 60]]
[[10 26 42]
 [58 74 90]]


In [85]:
#배열 인덱싱
print(d[0])
print(d[0,:])
print(d[:,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [17 18 19 20]]


In [92]:
import numpy as np

arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]])
print(arr[:, 2])
print(arr[1,2:])
print(arr[2,:2])

[ 3  7 11]
[7 8]
[ 9 10]


In [110]:
# 불린참조:참 또는 거짓으로 연산되는 것을 불린연산이라고 하는데 그러한 분린을 참조하는 것이다. 
# 트루에 해당되는 자료를 참조하도록 할 수 있다.
a=np.array([1,2,3])
b=np.array([True, False, True])
print(a)
#b에 저장된 값이 true인 위치의 a배열 요소 값을 참조하겠다는 뜻이다. 
print(a[b])#이것이 불린참조이다.
# 판다스에서도 많이 나온다. 데이터분석시에도 많이 나온다. 


[1 2 3]
[1 3]


In [97]:
#불린참조를 응용해보자.arr에서 4의 배수만 추출하고자 한다면?
#파이썬으로 한다면 for문이 바로 떠오를 것이다. 하지만 넘파이는 이것을 불린참조로 간단하게 해결 가능하다.
print(arr%4==0) #한줄로 매우 간단하게 나왔다.
print(arr[arr%4==0])#트루인 부분이 알아서 튀어나온다.
#단 두줄로 for문을 돌리지 않고 해결되었다.


[[False False False  True]
 [False False False  True]
 [False False False  True]]
[ 4  8 12]


In [99]:
a = np.arange(11,20)
print(a[np.array([0,3,5])])#0번과 3번과 5번 요소를 참조하는 것이다.
print(a[np.array([0,3,5,5,5,5,5,5])])#반복도 가능하다

[11 14 16]
[11 14 16 16 16 16 16 16]


In [117]:
# 불린참조는 행과 열단위로도 참조가 가능하다.

arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]])
print(arr[:,:])
print(arr[[2,0,1],:])
brr = arr
print(arr[:,:])
arr[1,0] = 50
print(brr)
# 카피를 하지 않았기에 이런 참사가 발생했다.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [50  6  7  8]
 [ 9 10 11 12]]


In [119]:
arr[1,0] = 5
crr = arr.copy()
arr[1,0] = 50
print(crr)

<built-in method copy of numpy.ndarray object at 0x000001C7CB34E790>


In [128]:
names = np.array(["kim","park","lee"])
data=np.array([[4,2],[0,2],[-1,2]])
print(names=="kim")
print(data[names=="kim"]) #kim이 트루기 때문에 첫번째 요소가 출력된다.
print(data[names=="kim",1]) #1번 요소에서 2번째 숫자를 참조했다.
print(names!="park")
print(data[names!="park"]) # 부정을 사용하여 2개의 리스트를 불러왔다.
print(data[names!="park", 0]) # 그 중 첫번째 요소를 가져온다.


SyntaxError: incomplete input (61662308.py, line 9)

In [131]:
print(~(names=="kim"))#첫번째 것과 정 반대이다. 물결무늬는 부정의 의미이다.
print((names=="kim")|(names=="lee")) # or문으로 사용도 가능하다.
print(data[(names=="kim")|(names=="lee")]) #그 것을 추출하는 것도 가능하다.

[False  True  True]
[ True False  True]
[[ 4  2]
 [-1  2]]


In [134]:
print(data < 0) 
data[data<0] = 0 
print(data)

[[False False]
 [False False]
 [False False]]
[[4 2]
 [0 2]
 [0 2]]


In [138]:
print(names, data)
(data[names=="lee"])= 999
print(data)

['kim' 'park' 'lee'] [[4 2]
 [0 2]
 [0 2]]
[[  4   2]
 [  0   2]
 [999 999]]


In [145]:
arr = np.zeros((8,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [144]:
brr = np.ones((1, 4))
print(arr[])

[[1. 1. 1. 1.]]


In [148]:
arr = np.zeros((8, 4))
for i in range(arr.shape[0]):
    arr[i] = i

print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [ ]:
# 사실 0차원을 1차원으로 대입하는 것은 안된다.
#[0,0,0,0] = 0 은 0차원에서 1차원으로 가는 것인데 원래는 성립되지 않는 식이다.
# 하지만 [0,0,0,0] = [0,0,0,0] 으로 바뀌게 된다. 
# [0,0,0,0] = 1 로 적으면 [1,1,1,1]로 바뀐다.
# 이것을 브로드캐스팅이라고 한다.