In [1]:
# 파이토치 문법
# 그동안에 했던 것은 텐서플로 기반으로 사용했다. 
# 케라스는 텐서플로 기반이다. 버젼은 두 가지가 존재한다. 우리가 한 것은 초보자 버젼이다. 간략한 설정을 부여 가능하다.
# 진짜 텐서플로는 자세하다. 공부할 것이 훨씬 많다. 
# 과거에는 텐서플로가 유행했었다. 지금은 텐서플로, 파이토치가 반반이다. 파이토치를 사용할 수 있는 사람도 요구한다.
# 파이토치는 쉬운 편이다. 케라스와 비슷한 수준이다. 
# 코딩 시간이 짧고 기능도 많다. 
# 취업처를 찾을 때 데이터라고 검색하자. 
# sql도 특강이 예정되어있다. 2일 정도 들을 예정이다. 
# LLM은 경력자를 많이 뽑는다.
# 텐서플로, 파이토치도 많이 뽑는 편이다.
# 파이토치는 활용하기 좋을 것이다. 바로 실습하면서 알아보자. 


In [2]:
# 딥러닝프레임워크는 여러가지가 있다. 텐서플로, 파이토치등등 존재한다.
# 과거는 텐서플로가 유행했으나 지금은 파이토치가 유행하는 시기이다. 파이토치는 튜토리얼이 존재한다. 
# https://tutorials.pytorch.kr/?_gl=1*1f3w7gi*_ga*NTQxMTA4OTQuMTY1NzM0MzMzMA..*_ga_LEHG248408*MTY1ODA2Mzg0NS4zLjEuMTY1ODA2Mzg0OC41Nw
# 한국어 파이토치 튜토리얼이다. 시간나면 여기서 배우자. 
# 파이토치는 용어를 배우는 것이 중요하다. 용어에서 막히는 경우가 종종 있다. 

In [3]:
# 파이토치 용어
# 파이토치라는 패키지는 딥러닝 프레임워크이다. 토치는 기본이 되는 네임스페이스다. 
# 넘파이하고 상당히 유사하다. 수학관련 함수가 많이 쓰인다. 
# 토치.오토그래드라고 해서 자동미분함수도 존재한다. 경사하강법도 전부 가능하다.
# 유튜브 영상도 존재하니 배우는 것은 제대로 배워보자. 
# 이런 것을 참고하여 공부하자. 

In [4]:
# 파이토치는 2가지 주요 특징이 있다. 
# 1. 넘파이와 유사하다. 선형대수에서 다루는 다양한 연산을 빠르게 수행 가능하다. 
#   GPU상에서 실행 가능한 n차원 텐서(다차원 배열)로 구성된다. 
#   데이터를 저장하고 다루는 단위는 벡터(1차원 형태로 구성),행렬(2차원 형태로 구성), 텐서(3차원 형태로 구성), 스칼라(0차원)가 존재한다. 
#   텐서는 3차원 이상부터 해당한다. 3차원이 여러개가 뭉쳐서 4차원, 5차원 이렇게 갈 것이다. 
#   또는 3차원 이상의 배열을 다차원 배열로 부른다. 
# 2. 신경망을 구성하고 학습하는 과정에서 자동으로 미분을 하게된다. 
#   외부적으로 구현되어져 있다. 
#   2차원 텐서를 나타낼때는 (배치사이즈(2차원 텐서), 차원) 로 표시한다. 
#   하나의 훈련데이터 크기가 256차원이라고 가정하자. 256개의 수치데이터들이 존재할 것이다. 이와 같은 데이터가 3000개가 있다면?
#   (3000,256)이 2차원 텐서일 것이다. 
#   컴퓨터가 한번에 처리하는 2차원 텐서의 크기를 말할 때 (3000,256) 이렇게 표시해야 한다. 
#   비전분야에서는 3차원 텐서가 주로 사용된다. 얘들은 (배치사이즈, 폭, 높이)로 표현된다. 
#   자연어 처리분야보다는 비전처리, 영상처리등이 여러 장의 사진을 쓰는 분야다보니 단위가 크다. 
#   이와 같은 데이터를 표현할 때 이미지가 있었는데 이런 이미지를 위로 쌓아올렸다고 이해하면 된다. 
#   (3000,1920,1028) 이런식으로 표시된다. 
#   자연어는 꽤 다르다. (배치사이즈, 길이(타임스텝), 벡터크기(디멘젼))으로 나타내는 3차원 텐서이다. 

In [5]:
# 문장이 이중리스트로 있다고 해보자. [[문장],[문장],....[n개의 문장]]
# 문장단위로 나누고 단어단위로 나눈 다음 2차원 텐서구조로 벡터로 표현하게 된다. 
# 3차원 공간에 임베딩을 한다면.
# 3차원 공간에 표현이 되어진다면 단어1 = [0.3,0.7,1.5] 와 같이 나타낼 것이다. 
# 이것이 어떻게 바뀌게 되느냐. 대괄호가 두 개가 있으며 각각의 단어들이 임베딩이 된다고 하자. 삼중리스트로 저런 숫자들이 나열된다.
# 대단원[문장[단어]]이런 식으로 나눠지게 되는 것이다. 
# [나는 사과를 좋아해, 나는 망고를 싫어해] 라고 된다면 [[[나는],[사과를],[좋아해]],[[나는],[망고를],[싫어해]]]
# 이런 식으로 3차원화하여 숫자화(토큰화)되어서 나타날 것이다. [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[10,11,12],[13,14,15]]]
# 훈련데이터를 이런 식으로 구성한다.
#
# 배치사이즈를 1로 했다고 가정하자. 
# 첫번째 배치를 훈련해보면 다음과 같이 훈련된다.  텐서크기는 [1,3,3]이 여러번 오는 모양이다. 
# 첫번째 텐서
# [[[[1,2,3],[4,5,6],[7,8,9]]]] 
# 두 번째 텐서
# [[[1,2,3],[10,11,12],[13,14,15]]]
# 
# 문장을 하나씩 읽어서 학습을 하게 된다. 
# 이후 백프라퍼게이션을 통해서 업데이트를 하게 된다.
#
# 배치사이즈를 2로 하면 
# 첫번째 텐서
# [[[[1,2,3],[4,5,6],[7,8,9]]]] 
# [[[1,2,3],[10,11,12],[13,14,15]]]
# 두번째 텐서
# [[[[1,2,3],[4,5,6],[7,8,9]]]] 
# [[[1,2,3],[10,11,12],[13,14,15]]]
# 이런 식으로 학습될 것이다. 
# 
# 문장을 전부 한바퀴 돌면 1에폭을 돌린 것이다. 
# 학습을 할 때 이런 구조적은 측면에서 용어의 정리가 필요하다. 
# 넘파이를 이용해서 텐서를 만들고 파이토치를 이용해서 텐서를 만들어보자. 

In [10]:
import numpy as np
# 넘파이로 텐서를 만드는 방법.
# 1차원 텐서를 만들어보자. 
t = np.array([1,2,3,4])
t
# 이게 1차원 텐서다. 

array([1, 2, 3, 4])

In [11]:
t.ndim # 텐서의 차원이다. 

1

In [12]:
t.shape # (4,)의 의미는 1행 4열 (1,4)를 의미한다.

(4,)

In [13]:
# 2차원 텐서는 2차원 리스트구조로 만들 수 있다. 
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

In [14]:
t # 2차원 배열이자 2차원 텐서이다. 

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [15]:
t.ndim # 똑같이 2차원 텐서이다. 

2

In [16]:
t.shape # 크기는 (4,3)이다

(4, 3)

In [18]:
pip install torch
# 먼저 파이토치를 설치하자. 

   ---------------------------------------- 0.0/192.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/192.3 MB 7.9 MB/s eta 0:00:25
   ---------------------------------------- 1.0/192.3 MB 13.3 MB/s eta 0:00:15
   ---------------------------------------- 2.1/192.3 MB 16.6 MB/s eta 0:00:12
    --------------------------------------- 3.3/192.3 MB 19.5 MB/s eta 0:00:10
    --------------------------------------- 4.2/192.3 MB 22.3 MB/s eta 0:00:09
    --------------------------------------- 4.2/192.3 MB 22.3 MB/s eta 0:00:09
    --------------------------------------- 4.2/192.3 MB 22.3 MB/s eta 0:00:09
    --------------------------------------- 4.6/192.3 MB 12.8 MB/s eta 0:00:15
   - -------------------------------------- 5.9/192.3 MB 14.4 MB/s eta 0:00:13
   - -------------------------------------- 7.0/192.3 MB 15.5 MB/s eta 0:00:12
   - -------------------------------------- 8.2/192.3 MB 16.3 MB/s eta 0:00:12
   - -------------------------------------- 9.3/192.3 MB 17.1

In [19]:
import torch

In [20]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])  # 플롯텐서, 인트텐서 등 텐서를 어떤 방식으로 만들지 나올 것이다. 
t                                                    # 어레이가 아니라. 텐서라고 표시된다. 

tensor([0., 1., 2., 3., 4., 5., 6.])

In [21]:
t.dim()            # 차원을 나타낸다. 

1

In [22]:
t.shape           # 괄호없이 모양보기

torch.Size([7])

In [23]:
t.size()          # 괄호가지고 모양보기
                  # 괄호가 있는 이유는 t가 이 함수(매서드)를 가지고 있다는 뜻이다. 괄호없으면 속성(어트리부트)라고 부른다. 
                  # 함수는 기능을 가지고 있다.
                  # 자동차(클래스)에서 파생된 내차(객체)가 달린다(함수)로 표현 가능하다.
                  # 여기서 t는 내차의 포지션이다. 일반적으로 Float같이 대문자로 시작하면 클래스 함수라고 정의한다. 
                  # (FloatTensor)클래스는 달리는 기능을 가진다. 여기서 내 차(t)라는 실체가 달리는(.size())것이다. 
                  # 클래스 괄호안에 객체의 재료를 담으면 객체가 생성된다. 그리고 그 객체를 함수로 동작시킨다. 
                  # 동작은 함수다. 달리기, 멈추기, 쌍라이트 등이다. 
                  # 속성은 info와 같다. 구동, 배기량 등을 말한다. 
                  # 속성과 함수는 구분되어야 한다. 
                  # 객체지향에 대해 제대로 이해하려면 1년이 넘게 걸린다. 
                  # 결론
                  # 클래스는 설계도면이다. 
                  # 객체는 설계도로 만들어진 하나의 실체이다. 
                  # 함수는 객체의 작동 매커니즘이다. 
                  # 속성은 객체의 특성, 스텟이다.
                    


torch.Size([7])

In [24]:
# 객체지향적이라는 말은 객체를 중심으로 프로그래밍한다는 것이다. 기존꺼 못쓰면 기존거를 재사용한다. 
# 기존에 가지고 있던 특성, 동작을 일부 수정,변경해서 새로 사용한다는 것이다. 
# 비용절약, 개발시간 단축, 안정성등의 장점이다. 
# 파이썬, 자바, C++ 모두가 객체지향적 언어이다. 
# 
# 코드로 무엇인가를 만들어서 진행하는 것은 절차지향적이라고 한다. 기존꺼 못쓰면 다른것을 계속 만들어야 한다. 
# 아예 새로 만드는 매커니즘이다. 과거에는 절차지향적 코딩을 많이했었다. 
# 어셈블리어등이 여기에 해당한다. 

In [25]:
t[3]            # 넘파이와 매커니즘은 동일히다. 

tensor(3.)

In [26]:
t[2:5]             

tensor([2., 3., 4.])

In [27]:
t[:5]          # 넘파이에 익숙하다면 어렵지 않다. 

tensor([0., 1., 2., 3., 4.])

In [28]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])

In [29]:
t.dim()        # 차원은 2차원이다. 

2

In [30]:
t.shape        # 모양은 4,3이다.   

torch.Size([4, 3])

In [31]:
t[:,1]         # 행은 전부 가져오고 두번째 차원을 가져오라는 이야기이다. 동일하다. 마이너스 인덱스도 가능하다. 

tensor([ 2.,  5.,  8., 11.])

In [32]:
t[:,1].size()  # 가능하다

torch.Size([4])

In [33]:
# 행렬의 덧셈뺄셈은 두 행렬의 크기가 같아야 가능했지만 넘파이는 브로드캐스팅이 가능했다.
# 행렬연산은 조건이 존재한다. 덧셈, 뻴셈을 하는 경우는 반드시 두 행렬의 크기가 같아야 한다.
# 행렬연산의 곱셈은 마지막차원과 첫번째차원이 일치해야 한다. 
# 자동으로 크기를 조절하게 해서 연산을 가능하게 만드는 것이 브로드캐스팅이다. 크기를 맞춰서 두 행렬이 연산 가능하게 하는 것이다. 
t1 = torch.FloatTensor([[1,1]])
t2 = torch.FloatTensor([[2,2]])

In [34]:
t1+t2 # 크기가 동일하면 무난하다. 

tensor([[3., 3.]])

In [35]:
t3 = torch.FloatTensor([[1,1]])
t4 = torch.FloatTensor([3])
t3+t4                           # 브로드캐스팅으로 1차원과 2차원이 더해졌다. 

tensor([[4., 4.]])

In [36]:
t5 = torch.FloatTensor([[1,3]])   # 1,2의 행렬이다. 
t6 = torch.FloatTensor([[3],[4]]) # 2,1의 행렬이다. 
t5+t6                             # 더해졌다.한쪽이 증식해서 맞춰진 것이다. 
                                  # [1,3]      [3,3]
                                  #         + 
                                  # [1,3]      [4,4]

tensor([[4., 6.],
        [5., 7.]])

In [37]:
t6+t5                             # 브로드캐스팅은 크기가 다르더라도 확장이 된다. 원하든 원하지 않든 이루어진다. 
                                  # 문제는 이 점을 간과하면 찾기가 어렵다는 것이다. 

tensor([[4., 6.],
        [5., 7.]])

In [38]:
m1 = torch.FloatTensor([[1, 2], [3, 4]]) # 2,2의 크기를 가진다. 
m2 = torch.FloatTensor([[1], [2]])       # 2,1의 크기를 가진다. 
                                         # 이 두 개를 곱해보자. 매트릭스 멀티플라이라고 부른다. 
                                         # 파이토치에서는 matmul이라고 쓴다. 

In [39]:
m1.matmul(m2)                            # 위에 (1)*1 + (2)*2 = 5이다.
                                         # 아래는 (3)*1 + (4)*2 = 11 이다. 

tensor([[ 5.],
        [11.]])

In [40]:
m2.matmul(m1)                            # 열이 2개가 있어야 행 2개랑 곱할 수 있다. 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1 and 2x2)

In [41]:
m1*m2 # 결과가 다르긴 하다. 증식해서 곱해진 것이다. 행은 행끼리, 열은 열끼리 곱해졌다.

tensor([[1., 2.],
        [6., 8.]])

In [42]:
# 평균을 구하는 것은 넘파이의 mean하고 비슷하다. 
t = torch.FloatTensor([1,2])
t

tensor([1., 2.])

In [43]:
t.mean() # 평균은 1.5로 나온다. 

tensor(1.5000)

In [44]:
t = torch.FloatTensor([[1,2],[3,4]])
t

tensor([[1., 2.],
        [3., 4.]])

In [45]:
t.mean() # 전체평균이 나온다. 

tensor(2.5000)

In [46]:
t.mean(dim=0) # 행 단위로 1번째 차원으로 계산하라는 것이다.열끼리 평균이 나왔다. axis = 1과 같은 효과이다. 

tensor([2., 3.])

In [47]:
t.mean(dim=1) # 열 단위로 1번째 차원을 계산하라는 것이다.행끼리 평균이 나왔다.  axis = 0과 같은 효과이다. 

tensor([1.5000, 3.5000])

In [50]:
t = torch.FloatTensor([[1,2],[3,4]])
t.sum()                                 # 내부숫자를 전부 더해버렸다. 

tensor(10.)

In [51]:
t.sum(dim=1)                           # 행끼리 더해져서 나왔다. 

tensor([3., 7.])

In [52]:
t.sum(dim=0)                           # 열 끼리 더해졌다. 

tensor([4., 6.])

In [53]:
t.max()                                # 모든 값 중 최댓값이 나왔다. 

tensor(4.)

In [54]:
t.max(dim=0)                          # 최대값이 나오고 argmax도 같이 나온다.              

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [56]:
t.max(dim=0)[1]                       # 물론 따로 추출도 가능하다. 

tensor([1, 1])

In [57]:
# 뷰
# 파이토치에는 뷰라고 하는 것이 존재한다. 
# 넘파이 시절 모양을 변경시킬때 reshape를 썼던 기억이 있을 것이다. 
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [58]:
ft.shape # 3차원의 구조이다. 

torch.Size([2, 2, 3])

In [59]:
ft.view([-1,3]) # 가끔 쓰이는 reshape 함수이다. 
# 뷰 함수는 텐서의 크기를 변경하는 함수이다. 
# 크기를 변경하는 방법은 -1,3으로 변경한다는 것이다. 즉 (?,3)으로 표현하는 것이다. 모르겠으니 알아서 하라는 것이다. 
# [2,2,3] 이라는 3차원 텐서를 2차원 텐서인 (?,3)으로 바꾸라는 것이다. 
# 12개의 요소들을 열을 3으로 확정하고 행의 개수는 알아서 계산한다.
# 12개의 요소로 구성되어져 있는 3차원 텐서를 열의 갯수가 3으로 고정된 2차원 텐서로 바꾸기에 (4,3) 텐서가 만들어진다. 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [60]:
ft.view([-1,3]).shape

torch.Size([4, 3])

In [61]:
ft.view([-1,5]).shape
# 약수관계에 없으면 애러가 뜨게 될 것이다. 

RuntimeError: shape '[-1, 5]' is invalid for input of size 12

In [63]:
ft.view([4,-1]) # 아까랑 비슷하게 뜨게 된다. 
# 그리고 ft(2,2,3)을 다시 바꿔서 (?,1,3)으로 바꿔보고 싶다고 하자. 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [65]:
ft.view([-1,1,3]) # 다양한 구조로 텐서를 변경할 수 있다. 

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])

In [66]:
# 스퀴즈 함수
ft=torch.FloatTensor([[0],[1],[2]])
ft                                    # (3,1) 행렬을 만들었다.

tensor([[0.],
        [1.],
        [2.]])

In [67]:
# 2차원 구조의 텐서를 1차원 구조의 텐서로 만들고자 한다면?
ft.squeeze()# 1차원으로 늘어졌다. 

tensor([0., 1., 2.])

In [68]:
ft2=torch.FloatTensor([[0,1],[2,3],[4,5]])
ft2           

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [69]:
ft2.squeeze() # 삭제 되지 않았다. 
              # 스퀴즈는 크기가 1인 차원을 제거해주는 함수이다. 즉 1에 해당하는 차원을 제거하는 목적으로 사용한다. 
              # 3행 2열이기에 제거되는 차원이 없다. 

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])

In [70]:
# 언스퀴즈(unsqueeze)
# 크기가 1인 차원을 특정위치에 추가하는 것이다. 스퀴즈와 반대이다. 
ft = torch.Tensor([0, 1, 2])
ft

tensor([0., 1., 2.])

In [71]:
# 크기가 1인 차원을 추가해보자. 
ft.unsqueeze(0)                # 첫번째 차원에 추가한 것이다. 변화가 없다. 행 부분이 1이다.

tensor([[0., 1., 2.]])

In [72]:
ft.unsqueeze(1)                # 두번째 차원에 추가한 것이다. (3,1)으로 바뀌었다. 열 부분이 1이다.

tensor([[0.],
        [1.],
        [2.]])

In [73]:
# 파이토치 자료형
# 파이토치는 실수형도 있지만 정수형도 존재한다. 
# float텐서는 32비트로 정의된다. 정수는 int텐서는 32비트와 64비트가 된다. 
# https://pytorch.org/docs/stable/tensors.html 이 사이트에서 확인이 가능하다.
# 64비트는 10에 300승 정도를 표현할 수 있다. 
# 16비트는 10에 30승 가량을 표현할 수 있다. 
# 정수는 정수를 표현하는 가장 큰 타입이 long타입이다. 8바이트를 잡아먹는다. 921경으 표현 가능하다. 
# 인티저는 4바이트를 잡아먹는다. 
# 그래서 엄청 큰 수는 float을 쓴다. 더 크면 double을 쓴다. 
# 이번에 long텐서를 만들어보자. 
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [74]:
# 만약 실수가 있고 정수가 있다면 정수로 통합된다. 
lt = torch.LongTensor([1., 2., 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [75]:
lt.float() # 일괄적으로 실수로 변환되었다. 

tensor([1., 2., 3., 4.])

In [80]:
bt = torch.ByteTensor([True, False, True, False])
print(bt)                                 # 불린은 바이트로 표시해도 지장없다. 
                                                 # unsigned int 8비트 라는 뜻이다. 
                                                 # 사실 불린은 1 또는 0으로 표현할 수 있다. 바이트텐서 이상의 공간을 쓸 필요는 없다. 
                                                 # uint는 0부터 255까지 표현 가능하다. 
                                                 


tensor([1, 0, 1, 0], dtype=torch.uint8)


In [81]:
bt.long() # 롱으로 바뀌었다.이제 아주 큰 수도 저장이 가능해진다. 

tensor([1, 0, 1, 0])

In [85]:
bt = torch.ByteTensor([255, False, True, False]) # 255까지 가능하다. 넘어가면 오버플로우 애러가 뜬다. 
print(bt)                                           

tensor([255,   0,   1,   0], dtype=torch.uint8)


In [91]:
bt = torch.LongTensor([1234567891234567891, False, True, False]) # 921경까지 가능하다. 
print(bt)   

tensor([1234567891234567891,                   0,                   1,
                          0])


In [92]:
bt = torch.FloatTensor([12345678912345678912345, False, True, False]) # 플롯은 그 이상의 숫자도 가능하다.
print(bt)   

tensor([1.2346e+22, 0.0000e+00, 1.0000e+00, 0.0000e+00])


In [93]:
# cat 함수
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
# 예전에는 .merge .join .concat등 많은 함수를 사용했다. 
# 여기서는 cat 함수를 쓴다. 

In [94]:
x

tensor([[1., 2.],
        [3., 4.]])

In [95]:
y

tensor([[5., 6.],
        [7., 8.]])

In [96]:
torch.cat([x,y]) # 합쳐졌다. 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [97]:
torch.cat([x,y],dim=0) # 디폴트이다. 첫 번째 차원이 늘어난다. 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [98]:
torch.cat([x,y],dim=1) # 두 번째 차원으로 늘어났다. 

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])

In [99]:
# 텐서들끼리 연산하는 경우가 종종 보인다. 
# 텐서들끼리 합쳐지는 경우가 있다. 중간중간 연산속에서 서로 다른 텐서를 연결하는 경우가 있을 것이다. 
# 이런 상황에서 cat은 유용하게 사용되어질 것이다. 

In [100]:
# 스태킹
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [101]:
x


tensor([1., 4.])

In [102]:
y

tensor([2., 5.])

In [103]:
z

tensor([3., 6.])

In [104]:
# 3개의 텐서가 존재하는 상태이다. 3개의 벡터를 모두 연결하려고 한다. 
torch.stack([x,y,z]) # 참고로 적은 순서대로 합쳐진다. 

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [105]:
torch.stack([x,z,y]) # 순서를 바꾸면 이러한 모양이 된다.

tensor([[1., 4.],
        [3., 6.],
        [2., 5.]])

In [106]:
# 원스 라이크, 제로스 라이크
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)                                        # 2,3의 크기를 가진 텐서이다. 
                                                # 텐서의 크기를 그대로 두되 새롭게 0 또는 1로 값을 채우는 것을 원할 때 쓴다. 

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [107]:
torch.ones_like(x)                              # 구조는 같고 내용은 전부 1로 바뀐다. 

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [109]:
torch.zeros_like(x)                             # 구조는 같고 내용은 전부 0으로 바뀐다. 

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [110]:
x = torch.FloatTensor([[1, 2], [3, 4]])        # 

In [111]:
x                                              # 2차원 구조의 텐서가 만들어진다. 

tensor([[1., 2.],
        [3., 4.]])

In [113]:
x*2                                            # 2를 곱했다.

tensor([[2., 4.],
        [6., 8.]])

In [114]:
x.mul(2)                                       # 2를 곱하는 방법이다. 

tensor([[2., 4.],
        [6., 8.]])

In [115]:
x.mul_(2)                                      # 만약에 함수 뒤에 언더바를 붙이면

tensor([[2., 4.],
        [6., 8.]])

In [116]:
x                                             # 덮어쓰기도 함께 수행된다는 것이다. 

tensor([[2., 4.],
        [6., 8.]])

In [117]:
result = 0                                    # 먼저 결과값을 저장해보자. 

In [119]:
def add(num):                                 # 외부로부터 값을 전달받는 함수가 있다고 해보자. 
    result +=num
    return result

In [120]:
add(3)                                        # result는 지역변수로 취급되어 접근할 수 없다고 나온 것이다. 
                                              # result는 바깥쪽에 선언되어져 있다. 전역변수이다. 
                                              # 만약 쓰고싶다면 

UnboundLocalError: cannot access local variable 'result' where it is not associated with a value

In [121]:
def add(num):                                 # 외부로부터 값을 전달받는 함수가 있다고 해보자. 
    result = 1
    result +=num
    return result

In [122]:
add(3)                                        # 함수 자체는 작동한다.

4

In [123]:
print(result)                                 # 지역변수와 전역변수는 구분된다. 함수는 블록 내에서만 사용된다. 
                                              # 함수 바깥에 있는 result는 전역변수이다. 

0


In [124]:
def add(num):                                
    global result
    result +=num
    return result

In [125]:
add(3)                                       # 글로벌을 써서 전역변수를 쓰면 된다. 
                                             # 

3

In [144]:
result1 = 0
result2 = 0

In [145]:
def add1(num):
    global result1
    result1 +=num
    return result1

In [146]:
print(add1(3))                               # 먼저 여기까지는 알 것이다. 
print(add1(4))                               # 함수는 계속 이어져서 사용될 것이다. 

3
7


In [147]:
def add2(num):
    global result2
    result2 += num
    return result2

In [148]:
print(add2(2))                  
print(add2(6))                               # 여기서 두 개의 계산기는 별개이다. 
                                             # 문제는 계산기가 비슷하다. 이거로 일일히 계산기를 만드는 것은 매우 비효율적이다. 
                                             # 그래서 클래스라는 개념을 사용한다. 
                                             # 클래스를 통해서 계산기를 여러개 만드는 상황을 정의하자는 것이다. 

2
8


In [161]:
class Calculator:
    def __init__(self):        # 클래스로부터 객체가 생성될때 자동으로 호출되는 함수이다. 생성자함수라고 부른다. 
        self.result = 0        # 객체에 대한 초기작업을 수행하는 부분이다. 
        print('생성자 호출됨') # 수행 정상적으로 이루어졌다. 

    def add(self, num):        # 함수를 호출한다. 
        print('add함수 호출됨')# 결과수행을 보자. 
        self.result += num     # 작동은 다음과 같이 이루어진다. 
        return self.result     # 결과를 리턴한다. 

In [162]:
# 객체 생성 
cal1 = Calculator()            # 실체가 만들어졌다. 
cal2 = Calculator()            # 객체를 두 번 호출했다. 

생성자 호출됨
생성자 호출됨


In [163]:
cal1.add(3)                    # 이렇게 함수가 제작되었다. 

add함수 호출됨


3

In [164]:
cal2.add(6)                    # 마음만 먹으면 객체를 얼마든지 만들 수 있게 된다. 

add함수 호출됨


6

In [496]:
# 선형회귀모델을 torch에서 구현하기.
# 선형회귀모델을 torch에서 만들때는 뉴럴 네트워크를 호출해야한다. 
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [497]:
torch.manual_seed(1)                    

In [498]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [499]:
# 가장 이상적인 회귀모델은 y = 2x가 가장 이상적인 모델일 것이다. 
# 이때 최적의 웨이트와 bias는 편미분도 하고 업데이트하고 코스트를 구해서 훈련할 것이다. 
x_train.shape

torch.Size([3, 1])

In [500]:
# 선형회귀모델을 만들때 w와 b를 선언해야 한다. 텐서플로시절에는 일일히 지정해주지 않았다. 
# 여기서는 모델을 만들때 가중치를 먼저 정의한다. 
W=torch.zeros(1,requires_grad = True)

In [501]:
W # 초기값은 0으로 줬다. 최종적으로 W는 2에 가까워질것이다. 
# requires_grad는 업데이트가 이루어지는 변수라는 뜻이다. 

tensor([0.], requires_grad=True)

In [502]:
B=torch.zeros(1,requires_grad = True) # bias도 똑같이 변수에 해당한다. 

In [477]:
# 초기모델은 y = 0*x+0에서 출발하는 것이다. 
# 현재는 x를 기어가는 모델이다. 
# w,b를 둘 다 업데이트 해야한다. 그래서 가설함수를 제작해야한다. 
# hx(가설함수) =W * x_train + B
hx = W * x_train + B
hx                            
# 초기값들인 0이다. 
# 아래로 볼록한 코스트 함수가 그려져 있어야 한다. 
# 그렇게 W와 B를 업데이트 해야한다. 편미분을 통해 업데이트 해야한다. 
# 텐서플로의 원 버젼도 이런 식으로 업데이트를 해야한다. 디테일하게 코딩해야한다. 

# 잠시후 여기를 반복해보자. 

tensor([[2.3593],
        [4.0671],
        [5.7749]], grad_fn=<AddBackward0>)

In [478]:
# 코스트 함수 정의하기
cost = torch.mean((hx - y_train)**2)  # 정답과 제출답의 제곱평균을 구한다. 이것이 코스트이다. 
cost                                  # 미분을 통해 w를 업데이트 한다. 경사하강법도 직접 구현해야 한다. 

tensor(0.0614, grad_fn=<MeanBackward0>)

In [479]:
optimizer = optim.SGD([W,B], lr=0.01) # 옵티마이저를 다음과 같이 설정했다. 
# 학습을 할 대상은 W와 B이다. 

In [480]:
optimizer.zero_grad()          # 미분을 해서 구한 기울기를 0으로 초기화해주는 부분이다. 
cost.backward()                # 백프라퍼게이션이 생각난다. W와 B에 대한 기울기가 계산이 된다. 
optimizer.step()               # 업데이트를 계속 진행한다. 

In [481]:
W # 업데이트가 되었다. 

tensor([1.7090], requires_grad=True)

In [476]:
B # 정답은 0이고 가까워지고 있다. 
  # 여기서 코스트 단계로 다시 가야한다.  이게 모델의 훈련 절차이다. 

tensor([0.6515], requires_grad=True)

In [458]:
# 이제 이걸 반복하면 된다. 

In [495]:
for epoch in range(2000):
    hx = W * x_train + B
    cost = torch.mean((hx - y_train)**2) 
    optimizer = optim.SGD([W,B], lr=0.01)  # 사실 이건 안에 있을 필요는 없다. 
    optimizer.zero_grad()      
    cost.backward()            
    optimizer.step()
    if epoch%100 == 0:
        print(epoch,W.item(),B.item(),cost.item() )

0 1.8666667938232422 0.800000011920929 18.66666603088379
100 1.9722299575805664 0.06312811374664307 0.0006002071313560009
200 1.9975632429122925 0.005539316684007645 4.621344942279393e-06
300 1.9997862577438354 0.0004860826884396374 3.557685701593982e-08
400 1.9999812841415405 4.265585448592901e-05 2.739284354902338e-10
500 1.9999983310699463 3.698257842188468e-06 1.9137285072606813e-12
600 1.9999998807907104 4.080832525232836e-07 1.8947806851624636e-14
700 2.0 1.0608626155317324e-07 0.0
800 2.0 1.0608626155317324e-07 0.0
900 2.0 1.0608626155317324e-07 0.0
1000 2.0 1.0608626155317324e-07 0.0
1100 2.0 1.0608626155317324e-07 0.0
1200 2.0 1.0608626155317324e-07 0.0
1300 2.0 1.0608626155317324e-07 0.0
1400 2.0 1.0608626155317324e-07 0.0
1500 2.0 1.0608626155317324e-07 0.0
1600 2.0 1.0608626155317324e-07 0.0
1700 2.0 1.0608626155317324e-07 0.0
1800 2.0 1.0608626155317324e-07 0.0
1900 2.0 1.0608626155317324e-07 0.0


In [486]:
cost

tensor(2.7755e-10, grad_fn=<MeanBackward0>)

In [487]:
W.item()*5+B.item()

9.999947471260384

In [504]:
# 미분계산을 자동으로 해서 반영하는 함수인 백워드 함수를 볼 수 있었다.
w = torch.tensor(2.0, requires_grad=True) # 기울기를 구해서 저장하겠다는 의미이다. 

In [505]:
y = w**2

In [506]:
y

tensor(4., grad_fn=<PowBackward0>)

In [507]:
z = 2*y+5

In [508]:
z

tensor(13., grad_fn=<AddBackward0>)

In [509]:
z.backward() # 미분을 한 상황이다. 

In [510]:
w.grad#z수식을 w로 미분한 값은 얼마인가?

tensor(8.)

In [568]:
# x변수가 3개가 있다고 해보자. 각각의 데이터에 대해 가중치가 붙을 것이다. 
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
# 문제를 보면 연립방정식을 풀게 될 듯 하다. 
# 수능점수 예측값을 도출하는 수식을 얻고자 한다. 
# 우리가 만든 모델을 가지고 앞으로 몇 점을 받을 것인지를 예측하고자 한다. 
# 데이터셋으로부터 만든 모델이 가지고 있는 웨이트와 바이어스를 곱하고 더해서 예측값을 도출하고자 하는게 목표일 것이다. 

In [569]:
x1_train.shape # 5행 1열이다. 

torch.Size([5, 1])

In [570]:
W1 = torch.zeros(1,requires_grad = True)
W2 = torch.zeros(1,requires_grad = True)
W3 = torch.zeros(1,requires_grad = True)
B  = torch.zeros(1,requires_grad = True)
# 초기화 작업이다. 

In [571]:
optimizer = optim.SGD([W1,W2,W3,B], lr=0.00001) # 안에 있을 필요없어서 바깥으로 뺐다. 0.01에서 0.1까지 부여하는게 일반적이다.
for epoch in range(2000):
    hx = W1 * x1_train + W2 * x2_train + W3 * x3_train + B
    cost = torch.mean((hx - y_train)**2) 
    optimizer.zero_grad()      
    cost.backward()            
    optimizer.step()
    if epoch%100 == 0:
        print(epoch,W1.item(),W2.item(),W3.item(),B.item(),cost.item() )

0 0.29401201009750366 0.2935999929904938 0.2973800003528595 0.0034199999645352364 29661.80078125
100 0.6735065579414368 0.6609680652618408 0.6762314438819885 0.007919806987047195 1.5636341571807861
200 0.6789458990097046 0.6549617052078247 0.676784336566925 0.008070035837590694 1.4976074695587158
300 0.6842513084411621 0.649121880531311 0.6773051619529724 0.008219091221690178 1.4350258111953735
400 0.6894262433052063 0.6434438228607178 0.6777952909469604 0.00836699828505516 1.375730276107788
500 0.6944740414619446 0.6379234194755554 0.6782552599906921 0.008513780310750008 1.3195109367370605
600 0.6993983387947083 0.6325562000274658 0.6786861419677734 0.008659474551677704 1.2662218809127808
700 0.7042022347450256 0.6273384094238281 0.6790884137153625 0.008804094977676868 1.2156964540481567
800 0.7088890075683594 0.622265636920929 0.6794635057449341 0.008947668597102165 1.1678179502487183
900 0.7134621739387512 0.6173338294029236 0.6798113584518433 0.009090210311114788 1.1224288940429688

In [555]:
# 뭔가 매우 이상하게 이루어졌다. 이것의 문제는 발산해버린 경우이다. 
# 코스트가 계속 올라가다가 아무것도 나오지 않는다. lr값이 너무 큰 경우다. 
# 또는 입력데이터에 대해 편차가 심한 경우이다. 정규화나 표준화가 이루어지지 않은 경우에 이렇게 된다. 
x1_train = torch.FloatTensor([[0.73], [0.93], [0.89], [0.96], [0.73]])
x2_train = torch.FloatTensor([[0.80], [0.88], [0.91], [0.98], [0.66]])
x3_train = torch.FloatTensor([[0.75], [0.93], [0.90], [1.00], [0.70]])
y_train = torch.FloatTensor([[1.52], [1.85], [1.80], [1.96], [1.42]])

In [556]:
W1 = torch.zeros(1,requires_grad = True)
W2 = torch.zeros(1,requires_grad = True)
W3 = torch.zeros(1,requires_grad = True)
B  = torch.zeros(1,requires_grad = True)

In [557]:
optimizer = optim.SGD([W1,W2,W3,B], lr=0.01) # 안에 있을 필요없어서 바깥으로 뺐다. 0.01에서 0.1까지 부여하는게 일반적이다.
for epoch in range(2000):
    hx = W1 * x1_train + W2 * x2_train + W3 * x3_train + B
    cost = torch.mean((hx - y_train)**2) 
    optimizer.zero_grad()      
    cost.backward()            
    optimizer.step()
    if epoch%100 == 0:
        print(epoch,W1.item(),W2.item(),W3.item(),B.item(),cost.item() )

0 0.029401199892163277 0.029360000044107437 0.02973800152540207 0.03420000150799751 2.9661800861358643
100 0.46306613087654114 0.46245095133781433 0.4696241617202759 0.5268245935440063 0.0035478007048368454
200 0.4669475853443146 0.46634650230407715 0.4749852418899536 0.5177428126335144 0.0034022568725049496
300 0.47018158435821533 0.4695737063884735 0.4796554744243622 0.5081755518913269 0.0032679885625839233
400 0.47335726022720337 0.47272154688835144 0.48423129320144653 0.4988046884536743 0.0031391982920467854
500 0.47647643089294434 0.47579237818717957 0.48871535062789917 0.4896276295185089 0.003015674650669098
600 0.47954025864601135 0.4787876307964325 0.4931096136569977 0.480640172958374 0.0028971899300813675
700 0.48254990577697754 0.48170921206474304 0.4974158704280853 0.4718383550643921 0.0027835420332849026
800 0.4855063855648041 0.4845585227012634 0.5016360282897949 0.4632183611392975 0.0026745288632810116
900 0.4884108006954193 0.4873371124267578 0.5057717561721802 0.4547764

In [558]:
# 코스트가 0인 경우는 거의 존재하지 않는다. 선형모델이 아닌 이상 나오지 않는다. 
# 팁으로 0.00001은 1e-5로 표시 가능하다. 
# 문제는 표준화하면 뭔가 답이 이상해진다. 그냥 0을 5개 붙이는게 더 정확한 듯 하다. 

In [572]:
W1.item()*73 + W2.item()*80 + W3.item()*75 + B.item() # 쉽지않다...

152.1425551418215

In [575]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [576]:
print(x_train.shape)
print(y_train.shape) 
# 먼저 연산을 하려면 행열을 맞춰야 한다. 
# W1,W2,W3를 하나로 합쳐서 행렬로 나타내보는 것도 방법일 것이다. 

torch.Size([5, 3])
torch.Size([5, 1])


In [577]:
W = torch.zeros((3,1),requires_grad = True) # 우리는 W를 한꺼번에 실행시키고 싶다. 
B = torch.zeros(1,requires_grad = True) 

In [578]:
optimizer=optim.SGD([W,B],lr=1e-5)

In [580]:
for epoch in range(2000):
    hx=x_train.matmul(W) + B
    cost=torch.mean((hx - y_train)**2)
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())
# 코스트는 떨어진다. 

0 9537.6943359375
100 5.752121448516846
200 5.510031700134277
300 5.2793989181518555
400 5.059759616851807
500 4.850369930267334
600 4.650723457336426
700 4.460408687591553
800 4.278825759887695
900 4.105560779571533
1000 3.940225124359131
1100 3.782344102859497
1200 3.6315715312957764
1300 3.4875869750976562
1400 3.3499629497528076
1500 3.218451738357544
1600 3.092745304107666
1700 2.9725329875946045
1800 2.8575236797332764
1900 2.7475745677948


In [594]:
print(W[1])

tensor([0.7106], grad_fn=<SelectBackward0>)


In [595]:
# 선형회귀 모델을 구현해보자. 
import torch
import torch.nn as nn
import torch.nn.functional as F

In [596]:
torch.manual_seed(1)

In [597]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [600]:
model = nn.Linear(1,1) #입력차원과 출력차원을 기재하면 된다. 입력변수가 1개고 출력변수도 1개이다. 

In [604]:
list(model.parameters()) # w와 b값을 볼 수 있다. 위가 w값, 밑이 b값이다. 

[Parameter containing:
 tensor([[-0.9414]], requires_grad=True),
 Parameter containing:
 tensor([0.5997], requires_grad=True)]

In [605]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)  # 사실상 변함이 없다. 아담대신 sgd고 퍼러미터를 직접 설정하는것 뿐이다. 

In [606]:
# hx부의 구문이 바뀔 것이다. 
for epoch in range(2000):
    hx = model(x_train)       # 모델값 자체다.
    cost = F.mse_loss(hx,y_train)         # 아까 한 mse이다. 
    optimizer.zero_grad()#미분을 해서 구한 기울기를 0으로 초기화해줌
    cost.backward() #W, b에 대한 기울기가 계산
    optimizer.step()#W,b에 대한 업데이트
    if epoch%100 ==0:
        print(epoch, cost.item())

0 33.67978286743164
100 0.223159059882164
200 0.1378987580537796
300 0.08521304279565811
400 0.05265649035573006
500 0.03253853693604469
600 0.020106827840209007
700 0.012424829415977001
800 0.00767778092995286
900 0.004744391422718763
1000 0.002931751310825348
1100 0.001811650930903852
1200 0.0011194882681593299
1300 0.0006917758728377521
1400 0.0004274678649380803
1500 0.0002641582686919719
1600 0.0001632305938983336
1700 0.00010086849943036214
1800 6.232853775145486e-05
1900 3.8514306652359664e-05


In [607]:
list(model.parameters())  # 값이 확실히 바뀌었다. 

[Parameter containing:
 tensor([[1.9943]], requires_grad=True),
 Parameter containing:
 tensor([0.0129], requires_grad=True)]

In [609]:
new_var =  torch.FloatTensor([[4.0]]) # 문제를 내보자. 

In [610]:
model(new_var) # 답이 나왔다. 이것은 predict와 같다. 

tensor([[7.9902]], grad_fn=<AddmmBackward0>)

In [611]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [612]:
model = nn.Linear(3,1) 

In [613]:
list(model.parameters()) 

[Parameter containing:
 tensor([[-0.1188,  0.2937,  0.0803]], requires_grad=True),
 Parameter containing:
 tensor([-0.0707], requires_grad=True)]

In [615]:
optimizer = torch.optim.SGD(model.parameters(),lr=1e-5)

In [618]:
for epoch in range(2000):
    hx = model(x_train)       
    cost = F.mse_loss(hx,y_train)         
    optimizer.zero_grad()
    cost.backward() 
    optimizer.step()
    if epoch%100 ==0:
        print(epoch, cost.item())

0 0.8999069333076477
100 0.8697694540023804
200 0.8411844372749329
300 0.8140530586242676
400 0.7883228063583374
500 0.7639040350914001
600 0.7407382726669312
700 0.7187463045120239
800 0.6978789567947388
900 0.6780833005905151
1000 0.6592813730239868
1100 0.6414272785186768
1200 0.6244879961013794
1300 0.6083956956863403
1400 0.5931113958358765
1500 0.5786016583442688
1600 0.5648104548454285
1700 0.5517212152481079
1800 0.5392765402793884
1900 0.5274502635002136


In [619]:
new_var =  torch.FloatTensor([[90,90,90]])

In [621]:
model(new_var) # 비슷하게 나왔다. 

tensor([[180.9370]], grad_fn=<AddmmBackward0>)

In [622]:
list(model.parameters())  # 퍼러미터도 꽤 잘 나왔다. 

[Parameter containing:
 tensor([[0.7909, 0.5203, 0.6999]], requires_grad=True),
 Parameter containing:
 tensor([-0.0545], requires_grad=True)]

In [ ]:
# 만약 단순 직선이 아니라 곡선형태의 모델이 만들어진다면 n차 방정식과 같은 모양새를 보일 것이다. 
# 이걸 클래스로 구현할 수 있어야 실전에 참여할 수 있다. 
# bert기반의 모델은 파이토치를 쓰는 경우가 많다. 