In [ ]:
# 프로젝트 팀이 짜여졌다. 프로젝트 관련하여 확인해보자
# 파이널 프로젝트에는 주도적으로 조를 편성할 수 있도록 할 것이다.
# 주제는 다양한 분야이다. 어떤 식으로 보여줄 것인가는 다르다. HTML, 자바스크립트, 플라스크로 보여주는 기반을 만들 것이다.
# 프로젝트는 이번달 말에 진행될 예정이다.주제를 미리 생각해 둘 필요는 있다.
# 태블로, 시각화를 하루 반 정도 할 예정이다. 취업때문에 태블로를 편성했다. 딥러닝 자연어처리, 이미지 파인튜닝도 해야한다.
# 그냥 바쁘다. 웹 프로그래밍도 공부해야한다. 코드를 아예 받고 시작할 것이다. 
# 자바스크립트는 어려울 수 있지만 HTML은 그나마 쉬울 것이다. 
# 대시보드
# 대시보드는 계기판을 말한다. 여러 정보들을 한꺼번에 볼 수 있는 그거 맞다.
# IT 쪽에서는 웹 페이지 안에 전체적인 다양한 정보들이 축약되어 모여있는 페이지를 말한다. 
# 시각적으로 분석결과를 보여주거나 앞으로 어떻게 예측되어지는지 보여주거나 실시간 정보를 보여주는 것 등 서비스를 할 수 있는
# 페이지로 이해하면 될 것이다. 

In [1]:
# 태깅. 객체명 인식을 해보자.
# 토픽 모델링이라고 이야기하는데 주어진 문서에서 중요한 의미를 추출하는 것을 말한다.
# 텍스트를 요약하는 방법들이 있다. 
# 케라스를 이용한 태깅작업은 전처리 과정과 연관이 깊다. 모델을 만드는 것 이전에 단어에 대한 인식을 시켜주는 것을 말한다.
# 언어중 이름인지 장소인지 집단인지 관계추출을 위한 자연어처리 영역에서도 중요하게 다룬다. 
# 사람이나 장소, 기관, 날짜 등 이 있을텐데 15일이라는 숫자가 있으면 컴퓨터는 날짜인지 알지 못한다. 
# 만약 유정이는 2018년 골드만삭스에 입사했다. 라고 말하면 유정(ps)이는 2018년(dt)에 골드만삭스(org)에 입사했다. 라고 표시하는 것을 원한다.
# 이 분야는 지도학습이 필요하다. 
# 과거에 발표된 약물의 종류에 대해 식별할 수 있도록 자질정보를 나타낸 것이 있다. 
# 먼저 글자로 된 이름들을 AI가 인식을 할 수 있도록 만들어야 한다. 
# 바이오태깅 기법이라고도 한다. 개체명 인식은 챗봇 등에서 필요한 주요 전처리 작업이면서 까다로운 작업이다. 
# 도메인 목적에 특화되도록 개체명 인식을 하기 위해 기존에 공개된 것을 사용하는게 아니라 우리가 제작할 수 있어야 한다. 
# 이미 공개된 개채명 인식기를 넘어 새로운 개채명 인식기를 만들 수 있어야 한다. 

In [2]:
# BIO표현(begin inside outside) 
# 시작, 내부, 외부로 나타낸다.
# 해리포터 보러가자 라고 하면 BIIIOOOO로 표현된다. 개체명은 B와 I로 표현된다. 개채명이 아닌 경우 O로 표기된다. 
# 해리포터(movie)보러 메가박스(theater)가자 라는 식으로 나눠진다. 
# New York는 위치를 나타낼 때 new(B-loc) york(iloc)로 표현한다. 
# 객체가 나타나면 그 객체에 대해 함께 태깅해야 한다. 
# https://github.com/machinereading/KoreanNERCorpus
# 한국어 객체명 인식기를 만들어내는 목적으로 위의 사이트를 이용 가능하다. 
# https://huggingface.co/datasets/bigbio/chemdner
# 의약품 관련 객체명을 인식하는 말뭉치(코퍼스)데이터가 정렬된 데이터셋이다. 
# 개체명 인식 데이터에서 COMLL2003은 개체명을 인식하기 위한 전통적인 영어 데이터셋이다.
# 문장과 문장사이의 구분은 공백으로 하도록 구성되어져있다.

In [3]:
# 토픽 모델링
# 토픽모델링은 중요한 단어를 추출하거나 중요한 문장을 추출하던지 문서를 요약하는 작업을 말한다. 
# 토픽모델링이라는 연구분야가 따로 존재한다. 사실 간단한 개념은 아니다. 
# 텍스트가 가지고있는 본래의 의미를 최대한 유지하면서 텍스트의 내용을 간략하게 줄이는 것을 말한다.
# 여러줄의 중요한 부분을 뽑아서 요약문을 만드는 작업을 할 수 있다(잠재 의미 분석)

In [4]:
# 문서요약 과정
# 문서요약은 3 과정으로 정의가능하다.
# I : 인터프리테이션 - 텍스트로 된 문자를 해석하고 컴퓨터가 이해할 수 있도록 표현하는 것을 말한다. 
# T : 트랜스포메이션 - 요약문으로 표현할 수 있도록 본래문장을 변형하는 것을 말한다.
# G : 제너레이션 - 최종적으로 요약문을 생성하는 것이다.
# 세 가지 과정을 순차적으로 진행하면서 요약하는 것이다.
# 문서를 요약할 때 입력 / 출력에 해당하는 문서, 목적에 해당하는 문서등으로 다양하게 분류 가능할 것이다.
# 문서는 한 개일 수도 있고 여러 개일수도 있다. 일반문서일 수 있고 전문문서일 수 있다. 특정 도메인 특화여부도 다르다.
# 분류에 따라 방법이 달라져야 한다. 도메인에 따라 차이가 크다.  
# 문서가 어느정도의 규모인지 고려를 해 볼 필요가 있다. 트위터와 뉴스는 길이가 다르다. 장르에 따라서도 다르다.
# 문서요약을 할 때에 중요한 것은 문서를 요약한 결과를 낼 때 단순히 주어진 문서 안에 있는 단어들을 조합해서 문서를 요약할 것인지 
# 문서 전체를 존재하지 않는 단어이지만 함축적인 의미를 담고있는 문장을 생성할 것인지 고려해야 한다. 
# 요약문에 대한 문장의 길이를 어떻게 할 것인지도 조정해야할 것이다. 
# 또는 편파성을 고려해야한다. 편파적인 요약문이 만들어지지 않도록 해야한다. AI는 의도적으로 편파적으로 만들 수 있다. 
# AI는 물어보는거 대답을 전부 잘해준다. 하지만 특정 이익집단에 의해 원하는 대답만 하게 만들 수도 있다. 
# 입력문서는 다양한 형태로 적용된다. 
# 일반적으로 사용자는 자신이 알고싶은 것을 요약해서 알려주는 것을 원할 것이다.사실상 정보를 알고 싶을 것이다. 
# 하지만 지금은 정보가 너무나도 많다. 차라리 요약을 해 주길 원한다. 
# 예전에는 지식을 책을 통해 접했지만 지금은 영상(그것도 축약형)으로 본다. 
# 전체 문서의 내용을 담고있으면서도 핵심 키가 되는 부분을 압축해서 전체적인 의미가 함의된 문장으로 표현할 수 있어야 한다. 
# 사용자가 원하는 방식으로 만들 수 있고 입력문서를 기반으로 요약할 수도 있을 것이다. 
# 사용 용도의 측면에서도 볼 수 있을 것이다. 중요한 정보만 원하느냐. 자세한 정보를 원하느냐의 차이도 존재한다. 
# 확장성 측면에서 생각할 수도 있다. 요약문이 원본 문서에 배경을 두는지 다른 문서와 비교할 때 최신의 문서를 제공할 수 있는지도
# 중요하다. 문서는 동적이어야 한다. 정적이면 안된다. 과거의 뉴스기사를 요약한 것이다.
# 중요한 단어들로부터 요약문서를 만드는 것이 추출방식이다. 추상은 전체적인 문서를 요약해서 문장으로 설명하는 것이다. 
# LDA기법은 행렬분해기법과 유사하다. 
# 기계학습 기반으로 토픽모델을 추출하는데 그것을 keyBERT라고 한다. 주제어를 잘 검출할 수 있도록 설계되었다. 
# 물론 한국어도 많이 나와있다. CTM같은 것들이다. 


In [5]:
# LSA
# LSA는 빈번하게 등장하는 단어들을 중요도를 계산해서 모델링하는 방식이다. 
# DTM과 TF-IDF를 기반으로 하기에 단어의 의미를 고려하지 못하는 LDA방식을 개선한 것이다. 
# 단어가 너무 빈번하면 중요하지 않다고 판단한 TF-IDF가 있었다. 물론 관사같이 연결용 단어는 중요하진 않다.
# 확실히 논문이 너무 많이 쏟아져나온다... 꽤 많다.
# LSA는 잠재의미분석(latent semantic analysis을 위한 새로운 대안이다. 
# 쉽고 빠르게 구현 가능하며 단어의 잠재적 의미를 이끌어 낼 수 있어서 유용하다.
# 이미 계산된 특성상 새로운 데이터를 계산하려고 하면 처음부터 다시 계산해야 한다. 업데이트도 쉽지 않다. 
# 신경망 기반의 단어표현방식이 각광받는 현재에는 잘 쓰이지는 않는다. 

In [6]:
# SVD
# SVD는 특이값 분해이다. 선형대수의 마지막 분야에 해당한다. 
# 취업이후 선형대수학, 통계학을 공부해보자. 
# A가 M*n일때 3개의 행렬의 곱으로 분해하는 것을 말한다. 
# 자신과 자신의 전치 행렬을 곱한 것이 직교행렬이다. 국민대 제출할 때 했었다. 
# 대각선을 제외한 곳의 원소가 모두 0인 행렬은 대각행렬이라고 한다. 
# svd로 나온 대각행렬의 대각 원소의 값을 행렬 A의 특이값이라고 한다
# 원래 행렬에서 행과 열을 바꾸는 것을 전치행렬이라고 한다. 예전에 넘파이때 배웠다. 
# 단위행렬은 대각선으로 1인 행렬이다. 
# 역행렬은 어느 행렬과 곱하여 단위행렬이 나오는 행렬을 말한다. 
# 직교행렬은 A 랑 A.T를 곱할 때 단위행렬을 만족하고 다시 바꾸면 역행렬이 되는 것을 직교행렬이라고 한다.
# 대각행렬은 대각형으로 내용이 존재하는 경우이다. 
# SVD는 풀 SVD(full SVD)와 절단된 SVD(turncated SVD)가 존재한다. 
# 일부 벡터를 삭제한 것인 절단 SVD는 LSA에 사용한다. 
# 일부 정보를 손실을 감안하고 절단한 것이다. 그래서 절단된 SVD로 기존행렬을 복구할 수는 없다. 
# t를 작게 잡아야 노이즈제거가 잘 이루어진다. 계산비용이 낮아지면서 상대적으로 중요하지 않은 정보를 정리할 수 있다.
# PCA알고리즘과 비슷하다. 
# TF-IDF는 단어의미 고려가 전혀 안되어있다. 절단된 SVD를 사용해서 차원축소를 시키고 단어의 잠재적 의미를 끌어오는 것이다. 

In [13]:
# 잠재 디레클레 할당(LDA)
# 문서가 있을 때 주제를 찾아내는 역할을 하는 프로세스를 말한다. 공공기관은 민원이 엄청나게 몰려온다. 
# 이러한 민원을 처리하는 것을 여러사람이 처리하는 시스템을 구축하는 것과 같다. 
# 논문을 통해서 지금도 많이 활용되고 있다. 지금도 잘 쓰인다는 이야기이다. 
# 모든 문서들은 토픽이 있고 토픽이 혼합되어있다고 가정한다. 
# 문서의 집합으로 부터 어떤 토픽이 존재하는지를 알아내기 위한 알고리즘이다.
# 단어의 순서는 상관없다. 문서에 사용할 단어의 개수를 정하면 토픽의 혼합을 확률분포에 기반하여 결정한다. 
# https://lettier.com/projects/lda-topic-modeling/
# 여기서 확인 가능하다. 
# 사실 LDA가 두 개다. 머신러닝 LDA(Linear Discriminant Analysis 선형 판별 분석) 알고리즘.
# 그리고 딥러닝 LDA(Latent Dirichlet Allocation 잠재 디리클레 할당)가 있다. 
# 
# 문서가 3개가 존재한다.
# 1. 저는 사과랑 바나나를 먹어요
# 2. 우리는 귀여운 강아지가 좋아요
# 3. 저의 깜찍하고 귀여운 강아지가 바나나를 먹어요
# 
# 1번의 토픽이 100%고 2번의 토픽이 100%라고 하자. 3번의 토빅은 2번 60%, 1번 40%로 토픽이 분포한다. 
# 수행과정은 다음과 같다.
# 1. 토픽의 개수 알려주기
# 2. 모든 단어를 토픽에 할당하기
# 3. 토픽을 재할당하는 과정을 거치기
# 위의 토픽은 과일과 강아지로 토픽이 분포가 될 것이다. 
# 뭔가 apriori와 느낌이 비슷하다. 차이점이 있다면 소비자가 원하는 물건을 추천하는 아페리오리와 토픽을 찾아서 종합하는 느낌의
# LDA는 느낌이 많이 다르다. 

In [23]:
# 솔직히 뭔 말인지 알아듣기 어렵다. 
# 다만 고객의 심리를 파악하는데에 디레클레 분포만큼 좋은 것도 없다. 고객의 인사이트를 파악하는데 사용하는 것이 디레클레이다. 
# 토픽모델링은 숨겨진 주제를 찾는 것이 핵심이기에 같은 주제끼리 묶어주는 역할도 한다. 
# 이건 비지도학습에 해당한다. 문서만 있지 그 문서가 무엇인지를 설명하지 않는 것이다. 
# 
# 제목은 없지만 기사/글이 10개가 있다고 해보자. 10개의 기사를 3가지의 카테고리로 나누어라! 라고 말한다면?
# 3가지 카테고리에 어떤 단어가 들어갈지를 먼저 생각할 것이다. 정치, 사회, 경제라고 나눈다고 가정하자.
# 각각의 단어의 분포를 파악해서 그 단어를 바탕으로 카테고리를 나눌 것이다.
# 컴퓨터는 문서가 있고 문서 안에 단어가 있다면 디리클레분포를 가정한다. 
# 토픽 내부에 문서와 단어를 하나씩 넣어보고 잠재적 의미를 찾는다. 
# 솔직히 프로덕트라는 말은 흔한 개념은 아니니까 생략하자.
# 1. 문고리 거래 하실분
# 2. 가방 나눔합니다. 문고리 드림
# 3. 비내면 거래로 합니다. 택배로 할께요.
# 이런 상황이면 1번은 문고리, 거래가 토픽이고 2번은 가방, 나눔, 문고리, 드림으로 핵심단어가 나온다. 3번은 비대면, 거래, 택배다.
# 여기서 마스크드 훈련을 했던 것처럼 토픽을 가려서 훈련한다. 골때린다. 
# 마스크드 훈련과 다른점은 가정에서부터 시작한다는 것이다. 
# 분포를 알고 있다면 가장 유사한 분포를 찾는 것이다. 즉 분포의 모양을 보는 것이 마스크드 모델과는 차이가 존재한다. 
# 단어의 순서가 상관없는 것이 마스크드 언어모델과 차이점이 있다. 

In [24]:
import numpy as np

In [25]:
A = np.array([[0,0,0,1,0,1,1,0,0],[0,0,0,1,1,0,1,0,0],[0,1,1,0,2,0,0,0,0],[1,0,0,0,0,0,0,1,1]])
print('DTM의 크기(shape) :', np.shape(A))
# 4,9짜리 행렬이다. 문서가 4개가 있고 9개의 단어가 존재한다고 가정하자. 

DTM의 크기(shape) : (4, 9)


In [26]:
# 원래의 행렬을 여러개로 나누고 특징값을 추출하는 것이다. 데이터에 잠재되어있는 특성값을 알아내는 것이다.
U, s, VT = np.linalg.svd(A, full_matrices = True) # 행렬을 분해한 것이다.
print('행렬 U :')
print(U.round(2))
print('행렬 U의 크기(shape) :',np.shape(U))

행렬 U :
[[ 0.24  0.75  0.    0.62]
 [ 0.51  0.44 -0.   -0.74]
 [ 0.83 -0.49 -0.    0.27]
 [ 0.   -0.    1.   -0.  ]]
행렬 U의 크기(shape) : (4, 4)


In [33]:
print('특이값 벡터 :')
print(s.round(2))
print('특이값 벡터의 크기(shape) :',np.shape(s))  

특이값 벡터 :
[2.69 2.05 1.73 0.77]
특이값 벡터의 크기(shape) : (4,)


In [34]:
VT.round(2)  

array([[ 0.  ,  0.31,  0.31,  0.28,  0.8 ,  0.09,  0.28,  0.  ,  0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ],
       [ 0.58, -0.  ,  0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.58,  0.58],
       [-0.  ,  0.35,  0.35, -0.16, -0.25,  0.8 , -0.16,  0.  ,  0.  ],
       [-0.  , -0.78, -0.01, -0.2 ,  0.4 ,  0.4 , -0.2 ,  0.  ,  0.  ],
       [-0.29,  0.31, -0.78, -0.24,  0.23,  0.23,  0.01,  0.14,  0.14],
       [-0.29, -0.1 ,  0.26, -0.59, -0.08, -0.08,  0.66,  0.14,  0.14],
       [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19,  0.75, -0.25],
       [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19, -0.25,  0.75]])

In [37]:
# 이렇게 4*4,1*4,9*9 의 행렬들이 만들어졌다.
# 이제 이것들을 원래대로 합치는 것이 일일 것이다. 

array([[ 0.64,  1.54,  0.  ,  0.47],
       [ 1.36,  0.91, -0.  , -0.57],
       [ 2.23, -1.  , -0.  ,  0.21],
       [ 0.  , -0.  ,  1.73, -0.  ]])

In [45]:
import numpy as np
from numpy.linalg import svd

# 4X4 Random 행렬 a 생성 
np.random.seed(121)
a = np.random.randn(4,4)
print(np.round(a, 3))

[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]
 [ 0.402 -0.191  1.404 -1.969]]


In [46]:
U, Sigma, Vt = svd(a)
print(U.shape, Sigma.shape, Vt.shape)
print('U matrix:\n',np.round(U, 3))
print('Sigma Value:\n',np.round(Sigma, 3))    # 원래는 대괄호 요소값이었지만 나머지가 0이라서 대각요소값들 4개가 존재하는 것이다. 
                                              # a행렬의 특이값이다. 
print('V transpose matrix:\n',np.round(Vt, 3))
# 문제는 시그마벨류는 1차원 구조이다. 이걸 2차원으로 바꿔야 한다. 

(4, 4) (4,) (4, 4)
U matrix:
 [[-0.079 -0.318  0.867  0.376]
 [ 0.383  0.787  0.12   0.469]
 [ 0.656  0.022  0.357 -0.664]
 [ 0.645 -0.529 -0.328  0.444]]
Sigma Value:
 [3.423 2.023 0.463 0.079]
V transpose matrix:
 [[ 0.041  0.224  0.786 -0.574]
 [-0.2    0.562  0.37   0.712]
 [-0.778  0.395 -0.333 -0.357]
 [-0.593 -0.692  0.366  0.189]]


In [47]:
np.diag(Sigma)                                 # 대각행렬을 만드는 식이다.

array([[3.4229581 , 0.        , 0.        , 0.        ],
       [0.        , 2.02287339, 0.        , 0.        ],
       [0.        , 0.        , 0.46263157, 0.        ],
       [0.        , 0.        , 0.        , 0.07935069]])

In [48]:
np.dot(U, np.diag(Sigma)) # 여기에 VT를 곱해야 할 것이다. 

array([[-0.27089043, -0.64373352,  0.40088514,  0.02985847],
       [ 1.31080548,  1.59109688,  0.05552549,  0.03724266],
       [ 2.24685261,  0.04537671,  0.16501535, -0.05271899],
       [ 2.20832581, -1.06956796, -0.15167705,  0.03519512]])

In [50]:
np.dot(np.dot(U, np.diag(Sigma)),Vt)  # 얼핏 비슷하게 나왔다. 잠재되어있는 자료를 이런 식으로 찾아낼 수 있다. 

array([[-0.21203317, -0.28492917, -0.57389821, -0.44031017],
       [-0.33011056,  1.18369457,  1.61537293,  0.36706247],
       [-0.01411931,  0.6296418 ,  1.70964074, -1.32698736],
       [ 0.40187312, -0.19142667,  1.40382596, -1.96876855]])

In [51]:
# 원본 행렬을 출력하고, SVD를 적용할 경우 U, Sigma, Vt 의 차원 확인 
np.random.seed(121)
matrix = np.random.random((6, 6))
print('원본 행렬:\n',matrix)
U, Sigma, Vt = svd(matrix, full_matrices=False)
print('\n분해 행렬 차원:',U.shape, Sigma.shape, Vt.shape)
print('\nSigma값 행렬:', Sigma)  # 특이값 행렬(잠재되어있는 특성) 차원축소를 한 것이다.


원본 행렬:
 [[0.11133083 0.21076757 0.23296249 0.15194456 0.83017814 0.40791941]
 [0.5557906  0.74552394 0.24849976 0.9686594  0.95268418 0.48984885]
 [0.01829731 0.85760612 0.40493829 0.62247394 0.29537149 0.92958852]
 [0.4056155  0.56730065 0.24575605 0.22573721 0.03827786 0.58098021]
 [0.82925331 0.77326256 0.94693849 0.73632338 0.67328275 0.74517176]
 [0.51161442 0.46920965 0.6439515  0.82081228 0.14548493 0.01806415]]

분해 행렬 차원: (6, 6) (6,) (6, 6)

Sigma값 행렬: [3.2535007  0.88116505 0.83865238 0.55463089 0.35834824 0.0349925 ]


In [54]:
num_components = 4
U_tr, Sigma_tr, Vt_tr = svd(matrix, num_components)
print('\nTruncated SVD 분해 행렬 차원:',U_tr.shape, Sigma_tr.shape, Vt_tr.shape)
print('\nTruncated SVD Sigma값 행렬:', Sigma_tr)
matrix_tr = np.dot(np.dot(U_tr,np.diag(Sigma_tr)), Vt_tr)  # output of TruncatedSVD

print('\nTruncated SVD로 분해 후 복원 행렬:\n', matrix_tr)


Truncated SVD 분해 행렬 차원: (6, 6) (6,) (6, 6)

Truncated SVD Sigma값 행렬: [3.2535007  0.88116505 0.83865238 0.55463089 0.35834824 0.0349925 ]

Truncated SVD로 분해 후 복원 행렬:
 [[0.11133083 0.21076757 0.23296249 0.15194456 0.83017814 0.40791941]
 [0.5557906  0.74552394 0.24849976 0.9686594  0.95268418 0.48984885]
 [0.01829731 0.85760612 0.40493829 0.62247394 0.29537149 0.92958852]
 [0.4056155  0.56730065 0.24575605 0.22573721 0.03827786 0.58098021]
 [0.82925331 0.77326256 0.94693849 0.73632338 0.67328275 0.74517176]
 [0.51161442 0.46920965 0.6439515  0.82081228 0.14548493 0.01806415]]


In [55]:
import numpy as np
from scipy.sparse.linalg import svds
from scipy.linalg import svd

np.random.seed(121)
matrix = np.random.random((6, 6))
print('원본 행렬:\n',matrix)
U, Sigma, Vt = svd(matrix, full_matrices=False)
print('\n분해 행렬 차원:',U.shape, Sigma.shape, Vt.shape)
print('\nSigma값 행렬:', Sigma)


num_components = 4
U_tr, Sigma_tr, Vt_tr = svds(matrix, k=num_components)
print('\nTruncated SVD 분해 행렬 차원:',U_tr.shape, Sigma_tr.shape, Vt_tr.shape)    # 만약 내가 추출하고 싶은 벡터가 4개라면 다음과 같아진다. 
print('\nTruncated SVD Sigma값 행렬:', Sigma_tr)                    
matrix_tr = np.dot(np.dot(U_tr,np.diag(Sigma_tr)), Vt_tr)  # output of TruncatedSVD

print('\nTruncated SVD로 분해 후 복원 행렬:\n', matrix_tr) # 값이 비슷하나 차이가 존재한다. 

원본 행렬:
 [[0.11133083 0.21076757 0.23296249 0.15194456 0.83017814 0.40791941]
 [0.5557906  0.74552394 0.24849976 0.9686594  0.95268418 0.48984885]
 [0.01829731 0.85760612 0.40493829 0.62247394 0.29537149 0.92958852]
 [0.4056155  0.56730065 0.24575605 0.22573721 0.03827786 0.58098021]
 [0.82925331 0.77326256 0.94693849 0.73632338 0.67328275 0.74517176]
 [0.51161442 0.46920965 0.6439515  0.82081228 0.14548493 0.01806415]]

분해 행렬 차원: (6, 6) (6,) (6, 6)

Sigma값 행렬: [3.2535007  0.88116505 0.83865238 0.55463089 0.35834824 0.0349925 ]

Truncated SVD 분해 행렬 차원: (6, 4) (4,) (4, 6)

Truncated SVD Sigma값 행렬: [0.55463089 0.83865238 0.88116505 3.2535007 ]

Truncated SVD로 분해 후 복원 행렬:
 [[0.19222941 0.21792946 0.15951023 0.14084013 0.81641405 0.42533093]
 [0.44874275 0.72204422 0.34594106 0.99148577 0.96866325 0.4754868 ]
 [0.12656662 0.88860729 0.30625735 0.59517439 0.28036734 0.93961948]
 [0.23989012 0.51026588 0.39697353 0.27308905 0.05971563 0.57156395]
 [0.83806144 0.78847467 0.93868685 0.72673231 

In [56]:
# 이게 실제로는 어떻게 쓰일지 알아보자. 
import pandas as pd
import urllib.request
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

In [57]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [68]:
data = pd.read_csv('abcnews-date-text.csv') # error_bad_lines=False는 오류가 있으면 건너뛰라는 소리이다. 

In [69]:
data

publish_date                                      headline_text
0            20030219  aba decides against community broadcasting lic...
1            20030219     act fire witnesses must be aware of defamation
2            20030219     a g calls for infrastructure protection summit
3            20030219           air nz staff in aust strike for pay rise
4            20030219      air nz strike to affect australian travellers
...               ...                                                ...
1082163      20170630  when is it ok to compliment a womans smile a g...
1082164      20170630                   white house defends trumps tweet
1082165      20170630     winter closes in on tasmania as snow ice falls
1082166      20170630  womens world cup australia wins despite atapat...
1082167      20170630          youtube stunt death foreshadowed by tweet

[1082168 rows x 2 columns]

In [70]:
# 헤드라인 텍스트는 제목에 해당하는 부분이다보니 많이 중요하다. 
text = data[['headline_text']]
text.head(5)

headline_text
0  aba decides against community broadcasting lic...
1     act fire witnesses must be aware of defamation
2     a g calls for infrastructure protection summit
3           air nz staff in aust strike for pay rise
4      air nz strike to affect australian travellers

In [71]:
text['headline_text'] = text.apply(lambda row: nltk.word_tokenize(row['headline_text']), axis=1) # 단어단위로 토큰화를 한 것이다. 
                                                                                                  # 확실히 이런 것은 코랩에서 하는 것이 낫다. 

C:\Users\user\AppData\Local\Temp\ipykernel_12616\443543600.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text['headline_text'] = text.apply(lambda row: nltk.word_tokenize(row['headline_text']), axis=1)


In [72]:
text                   

headline_text
0        [aba, decides, against, community, broadcastin...
1        [act, fire, witnesses, must, be, aware, of, de...
2        [a, g, calls, for, infrastructure, protection,...
3        [air, nz, staff, in, aust, strike, for, pay, r...
4        [air, nz, strike, to, affect, australian, trav...
...                                                    ...
1082163  [when, is, it, ok, to, compliment, a, womans, ...
1082164             [white, house, defends, trumps, tweet]
1082165  [winter, closes, in, on, tasmania, as, snow, i...
1082166  [womens, world, cup, australia, wins, despite,...
1082167   [youtube, stunt, death, foreshadowed, by, tweet]

[1082168 rows x 1 columns]

In [73]:
# 불용어를 제거해야할 듯 하다. 
from nltk.corpus import stopwords
stop = stopwords.words('english')
text['headline_text'] = text['headline_text'].apply(lambda x: [word for word in x if word not in (stop)])  # 단어가 스탑이라는 워드에 없으면 추가하라는 뜻이다. 
print(text.head(5)) 
# 3인칭 단수를 1인칭으로 바꾸거나 크기가 작은 단어들을 제거하는 작업 등을 해야할 듯 하다. 

                                       headline_text
0   [aba, decides, community, broadcasting, licence]
1    [act, fire, witnesses, must, aware, defamation]
2     [g, calls, infrastructure, protection, summit]
3          [air, nz, staff, aust, strike, pay, rise]
4  [air, nz, strike, affect, australian, travellers]


C:\Users\user\AppData\Local\Temp\ipykernel_12616\1467219579.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text['headline_text'] = text['headline_text'].apply(lambda x: [word for word in x if word not in (stop)])  # 단어가 스탑이라는 워드에 없으면 추가하라는 뜻이다.


In [74]:
from nltk.stem import WordNetLemmatizer   # 레머타이저는 3인칭 단수에 해당하는 단어를 1인칭으로 변환하기 위해서 사용한 것이다.
text['headline_text'] = text['headline_text'].apply(lambda x: [WordNetLemmatizer().lemmatize(word, pos='v') for word in x])
print(text.head(5))

                                       headline_text
0       [aba, decide, community, broadcast, licence]
1      [act, fire, witness, must, aware, defamation]
2      [g, call, infrastructure, protection, summit]
3          [air, nz, staff, aust, strike, pay, rise]
4  [air, nz, strike, affect, australian, travellers]


C:\Users\user\AppData\Local\Temp\ipykernel_12616\1264568339.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text['headline_text'] = text['headline_text'].apply(lambda x: [WordNetLemmatizer().lemmatize(word, pos='v') for word in x])


In [75]:
# 길이 3이하 단어 제거
tokenized_doc = text['headline_text'].apply(lambda x: [word for word in x if len(word) > 3])
print(tokenized_doc[:5])

0       [decide, community, broadcast, licence]
1      [fire, witness, must, aware, defamation]
2    [call, infrastructure, protection, summit]
3                   [staff, aust, strike, rise]
4      [strike, affect, australian, travellers]
Name: headline_text, dtype: object


In [76]:
# 역토큰화 (토큰화 작업을 되돌림)
detokenized_doc = []
for i in range(len(text)):
    t = ' '.join(tokenized_doc[i])
    detokenized_doc.append(t)

# 다시 text['headline_text']에 재저장
text['headline_text'] = detokenized_doc

C:\Users\user\AppData\Local\Temp\ipykernel_12616\876560129.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  text['headline_text'] = detokenized_doc


In [77]:
text['headline_text'] # 대괄호 없애고 원래 상태로 되돌린 상태다.

0                decide community broadcast licence
1                fire witness must aware defamation
2             call infrastructure protection summit
3                            staff aust strike rise
4               strike affect australian travellers
                             ...                   
1082163               compliment womans smile guide
1082164              white house defend trump tweet
1082165             winter close tasmania snow fall
1082166    womens world australia despite atapattus
1082167        youtube stunt death foreshadow tweet
Name: headline_text, Length: 1082168, dtype: object

In [78]:
# 상위 1,000개의 단어를 보존 
vectorizer = TfidfVectorizer(stop_words='english', max_features= 1000) # 벡터라이저의 스탑워드, 글자수를 지정했다.
X = vectorizer.fit_transform(text['headline_text'])                    # 벡터로 변환하였다. 

# TF-IDF 행렬의 크기 확인
print('TF-IDF 행렬의 크기 :',X.shape)

TF-IDF 행렬의 크기 : (1082168, 1000)


In [80]:
vectorizer.vocabulary_ 
# 뉴스기사의 제목들을 가져왔다. 
# 그리고 제목들의 불용어 제거, 동사를 1인칭으로 변환, 길이변환을 하였다.
# 그리고 리스트안에 담겨져있던 자료들을 변환하기 위해 원래상태로 되돌렸다.
# 즉 원래기사에서 불필요한 단어를 뺀 것이다. 
# TFIDF에서 함수를 집어넣은 것이다. 
# 여기까지가 토핑모델링의 준비단계인 것이다. 
# 문서에서 토픽이 무엇인지 정한만큼 각각의 문서가 어사인이 되어가는데 키워드가 무엇인지 뽑아내야한다. 

{'decide': 255,
 'community': 191,
 'licence': 521,
 'witness': 981,
 'infrastructure': 457,
 'protection': 678,
 'summit': 858,
 'staff': 833,
 'aust': 59,
 'strike': 847,
 'rise': 745,
 'affect': 16,
 'australian': 61,
 'jump': 486,
 'record': 707,
 'break': 112,
 'aussie': 57,
 'waste': 962,
 'match': 551,
 'address': 13,
 'security': 782,
 'council': 213,
 'iraq': 469,
 'australia': 60,
 'million': 563,
 'celebrate': 150,
 'plan': 629,
 'ahead': 22,
 'boost': 105,
 'water': 964,
 'supply': 860,
 'unite': 936,
 'state': 838,
 'dismiss': 274,
 'report': 724,
 'troop': 925,
 'british': 116,
 'arrive': 48,
 'lead': 508,
 'double': 279,
 'bushfire': 125,
 'victims': 946,
 'urge': 943,
 'businesses': 127,
 'prepare': 656,
 'attack': 54,
 'final': 342,
 'defeat': 258,
 'fuel': 371,
 'leave': 515,
 'miss': 567,
 'fund': 372,
 'bank': 74,
 'home': 429,
 'help': 416,
 'youth': 996,
 'chief': 160,
 'fail': 321,
 'secure': 781,
 'councillor': 214,
 'protect': 677,
 'heritage': 417,
 'welcome':

In [96]:
from sklearn.decomposition import LatentDirichletAllocation # 사이킷런에는 그게 구현이 되어져있다. 

In [97]:
lda_model = LatentDirichletAllocation(n_components=10, learning_method='online', random_state=777, max_iter=1)
# https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html
# 이것에 대한 설명서이다.
# 토픽의 갯수는 10개로 설정된 것이다. 가장 중요한 수치이다. 
# 교육메서드는 디폴트가 배치이다. 학습을 하는 과정에서 업데이트와 관련된 메서드이다. 
# 온라인이 좀 더 빠르다. 데이터가 큰 경우에 해당한다. 데이터가 적으면 배치가 좀 더 빠르다. 
# max iter는 에폭이라고 보면 된다. 성능을 높이고 싶다면 맥스이터를 높이게 된다. 
# n_job은 최대의 성능을 가지고 연산했으면 좋겠다면 -1로 설정하면 된다. 모든 cpu는 연산에 참여할 것이다. 
# 토픽은 10개이다. 1000개의 단어중에서 주요도가 높은 10개인 것이다. 

In [98]:
lda_top = lda_model.fit_transform(X)

In [99]:
terms=vectorizer.get_feature_names_out()  # 모든 피쳐들이 나오게 된다. 1000개 가량이다.
terms

array(['2013', '2014', '2015', '2016', 'abbott', 'aboriginal', 'abuse',
       'accc', 'accept', 'access', 'accident', 'accuse', 'action',
       'address', 'adelaide', 'admit', 'affect', 'afghan', 'afghanistan',
       'africa', 'agree', 'agreement', 'ahead', 'airport', 'alcohol',
       'alert', 'alice', 'allegations', 'allege', 'allow', 'ambulance',
       'amid', 'andrew', 'anger', 'angry', 'animal', 'announce', 'answer',
       'anti', 'anzac', 'apologise', 'appeal', 'appoint', 'approval',
       'approve', 'april', 'army', 'arrest', 'arrive', 'asbestos', 'asia',
       'asian', 'assault', 'asylum', 'attack', 'attempt', 'august',
       'aussie', 'aussies', 'aust', 'australia', 'australian',
       'australians', 'australias', 'authorities', 'avoid', 'await',
       'award', 'away', 'baby', 'baghdad', 'bail', 'bali', 'bangladesh',
       'bank', 'base', 'bash', 'battle', 'beach', 'beat', 'beattie',
       'beef', 'begin', 'bendigo', 'benefit', 'best', 'better', 'bike',
       'bik

In [100]:
lda_model.components_[0]        # 단어들의 중요도이다. 

array([1.00001533e-01, 1.00001269e-01, 1.00004179e-01, 1.00009783e-01,
       1.00003277e-01, 1.00005085e-01, 1.00008228e-01, 1.00005611e-01,
       1.00005647e-01, 1.00005891e-01, 1.00003852e-01, 1.00009243e-01,
       2.21950370e+03, 1.00005136e-01, 1.00012732e-01, 1.00006707e-01,
       1.00006758e-01, 1.00002416e-01, 1.00003071e-01, 1.00006781e-01,
       1.00005235e-01, 1.00007553e-01, 1.00007442e-01, 1.00018055e-01,
       1.00006315e-01, 1.00005805e-01, 1.00001334e-01, 1.00004811e-01,
       1.00010464e-01, 1.00005187e-01, 5.68722498e+02, 1.00007276e-01,
       1.00002793e-01, 1.00005508e-01, 1.00005284e-01, 1.00007886e-01,
       1.00008474e-01, 1.00004393e-01, 1.00007032e-01, 1.00005811e-01,
       1.10705722e+03, 1.00005659e-01, 1.00009460e-01, 1.00004993e-01,
       1.00006201e-01, 1.00004432e-01, 1.00006869e-01, 3.93491018e+03,
       1.00004439e-01, 1.00006127e-01, 1.00002532e-01, 1.00007665e-01,
       1.00007779e-01, 1.00002561e-01, 1.00009086e-01, 1.32470301e+03,
      

In [106]:
def get_topics(comp, fn, n=5):
    for idx, topic in enumerate(comp):
        print("Topic %d:" % (idx+1), [(fn[i], topic[i].round(2)) for i in topic.argsort()[:-n - 1:-1]])
#         print(idx, topic)

In [107]:
get_topics(lda_model.components_, terms) # 토픽 상위 5개를 출력한 것이다. 

Topic 1: [('government', 8725.19), ('sydney', 8393.29), ('queensland', 7720.12), ('change', 5874.27), ('home', 5674.38)]
Topic 2: [('australia', 13691.08), ('australian', 11088.95), ('melbourne', 7528.43), ('world', 6707.7), ('south', 6677.03)]
Topic 3: [('death', 5935.06), ('interview', 5924.98), ('kill', 5851.6), ('jail', 4632.85), ('life', 4275.27)]
Topic 4: [('house', 6113.49), ('2016', 5488.19), ('state', 4923.41), ('brisbane', 4857.21), ('tasmania', 4610.97)]
Topic 5: [('court', 7542.74), ('attack', 6959.64), ('open', 5663.0), ('face', 5193.63), ('warn', 5115.01)]
Topic 6: [('market', 5545.86), ('rural', 5502.89), ('plan', 4828.71), ('indigenous', 4223.4), ('power', 3968.26)]
Topic 7: [('charge', 8428.8), ('election', 7561.63), ('adelaide', 6758.36), ('make', 5658.99), ('test', 5062.69)]
Topic 8: [('police', 12092.44), ('crash', 5281.14), ('drug', 4290.87), ('beat', 3257.58), ('rise', 2934.92)]
Topic 9: [('fund', 4693.03), ('labor', 4047.69), ('national', 4038.68), ('council', 40

In [108]:
# 공개된 소설이나 책을 이용하여 주제를 파악하는것에 유용하다. 
# 데이터를 준비하여 LDA를 적용하여 나름대로 요약하는 것이다. 
# 각 주제별로 준비하는 것이다. 
# 한국어로 토크나이즈를 한다면 명사, 동사를 기준으로 나누는 작업을 해 줘야 할 것이다. 

In [109]:
# NLI는 두 문장의 유사성을 확인하여 관련이 있는지 모순되는지 중립인지를 확인하는 것이다.
# 한국어 데이터셋이 있다. tpu를 써야한다. 

In [110]:
import os
import pandas as pd
import numpy as np
from tqdm import tqdm
import urllib.request
from sklearn import preprocessing
import tensorflow as tf
from transformers import BertTokenizer, TFBertModel
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

In [111]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/kakaobrain/KorNLUDatasets/master/KorNLI/multinli.train.ko.tsv", filename="multinli.train.ko.tsv")
urllib.request.urlretrieve("https://raw.githubusercontent.com/kakaobrain/KorNLUDatasets/master/KorNLI/snli_1.0_train.ko.tsv", filename="snli_1.0_train.ko.tsv")

('snli_1.0_train.ko.tsv', <http.client.HTTPMessage at 0x1f931167790>)

In [112]:
# 검증 데이터 다운로드
urllib.request.urlretrieve("https://raw.githubusercontent.com/kakaobrain/KorNLUDatasets/master/KorNLI/xnli.dev.ko.tsv", filename="xnli.dev.ko.tsv")

('xnli.dev.ko.tsv', <http.client.HTTPMessage at 0x1f931182ed0>)

In [113]:
# 테스트 데이터 다운로드
urllib.request.urlretrieve("https://raw.githubusercontent.com/kakaobrain/KorNLUDatasets/master/KorNLI/xnli.test.ko.tsv", filename="xnli.test.ko.tsv")

('xnli.test.ko.tsv', <http.client.HTTPMessage at 0x1f92ef6d110>)

In [114]:
train_snli = pd.read_csv("snli_1.0_train.ko.tsv", sep='\t', quoting=3)
train_xnli = pd.read_csv("multinli.train.ko.tsv", sep='\t', quoting=3)
val_data = pd.read_csv("xnli.dev.ko.tsv", sep='\t', quoting=3)
test_data = pd.read_csv("xnli.test.ko.tsv", sep='\t', quoting=3)

In [115]:
train_snli.head()  

sentence1                  sentence2     gold_label
0  말을 탄 사람이 고장난 비행기 위로 뛰어오른다.  한 사람이 경쟁을 위해 말을 훈련시키고 있다.        neutral
1  말을 탄 사람이 고장난 비행기 위로 뛰어오른다.   한 사람이 식당에서 오믈렛을 주문하고 있다.  contradiction
2  말을 탄 사람이 고장난 비행기 위로 뛰어오른다.         사람은 야외에서 말을 타고 있다.     entailment
3          카메라에 웃고 손을 흔드는 아이들          그들은 부모님을 보고 웃고 있다        neutral
4          카메라에 웃고 손을 흔드는 아이들                    아이들이 있다     entailment

In [116]:
train_xnli.head()

sentence1  \
0         개념적으로 크림 스키밍은 제품과 지리라는 두 가지 기본 차원을 가지고 있다.   
1  시즌 중에 알고 있는 거 알아? 네 레벨에서 다음 레벨로 잃어버리는 거야 브레이브스...   
2                  우리 번호 중 하나가 당신의 지시를 세밀하게 수행할 것이다.   
3                       어떻게 아세요? 이 모든 것이 다시 그들의 정보다.   
4  그래, 만약 네가 테니스화 몇 개를 사러 간다면, 나는 왜 그들이 100달러대에서 ...   

                              sentence2  gold_label  
0           제품과 지리학은 크림 스키밍을 작동시키는 것이다.     neutral  
1            사람들이 기억하면 다음 수준으로 물건을 잃는다.  entailment  
2  우리 팀의 일원이 당신의 명령을 엄청나게 정확하게 실행할 것이다.  entailment  
3                        이 정보는 그들의 것이다.  entailment  
4                       테니스화의 가격은 다양하다.     neutral

In [120]:
# 결합 후 섞기
train_data = train_snli.append(train_xnli)
train_data = train_data.sample(frac=1)
# 콘트레디션은 서로 상반되는 것들이다.
# 엔테일먼트가 관련있는 것이고 뉴트럴은 애매한 경우이다.
# 이 자료들은 영국의 자료를 한국어로 번역한 것이다. 그래서 애매한 것이다.

AttributeError: 'DataFrame' object has no attribute 'append'

In [121]:
def drop_na_and_duplciates(df):   # 중복제거하기
  df = df.dropna()
  df = df.drop_duplicates()
  df = df.reset_index(drop=True)
  return df

In [122]:
print('훈련용 샘플 개수 :',len(train_data))
print('검증용 샘플 개수 :',len(val_data))
print('테스트용 샘플 개수 :',len(test_data))

NameError: name 'train_data' is not defined

In [ ]:
tokenizer = BertTokenizer.from_pretrained("klue/bert-base")
max_seq_len = 128
sent1 = train_data['sentence1'].iloc[0]
sent2 = train_data['sentence2'].iloc[0]

print(sent1)
print(sent2)

In [ ]:
encoding_result = tokenizer.encode_plus(sent1, sent2, max_length=max_seq_len, pad_to_max_length=True)
print(encoding_result['input_ids'])
# 어제하고 다른 점은 문장이 두 개가 들어간다는 점이다. 

In [ ]:
print(encoding_result['attention_mask'])

In [ ]:
def convert_examples_to_features(sent_list1, sent_list2, max_seq_len, tokenizer):

    input_ids, attention_masks, token_type_ids = [], [], []

    for sent1, sent2 in tqdm(zip(sent_list1, sent_list2), total=len(sent_list1)):
        encoding_result = tokenizer.encode_plus(sent1, sent2, max_length=max_seq_len, pad_to_max_length=True)

        input_ids.append(encoding_result['input_ids'])
        attention_masks.append(encoding_result['attention_mask'])
        token_type_ids.append(encoding_result['token_type_ids'])

    input_ids = np.array(input_ids, dtype=int)
    attention_masks = np.array(attention_masks, dtype=int)
    token_type_ids = np.array(token_type_ids, dtype=int)

    return (input_ids, attention_masks, token_type_ids)

In [ ]:
X_train = convert_examples_to_features(train_data['sentence1'], train_data['sentence2'], max_seq_len=max_seq_len, tokenizer=tokenizer)

In [ ]:
# 최대 길이: 128
input_id = X_train[0][0]
attention_mask = X_train[1][0]
token_type_id = X_train[2][0]

print('단어에 대한 정수 인코딩 :',input_id)
print('어텐션 마스크 :',attention_mask)
print('세그먼트 인코딩 :',token_type_id)
print('각 인코딩의 길이 :', len(input_id))
print('정수 인코딩 복원 :',tokenizer.decode(input_id))

In [ ]:
X_val = convert_examples_to_features(val_data['sentence1'], val_data['sentence2'], max_seq_len=max_seq_len, tokenizer=tokenizer)

In [ ]:
# 최대 길이: 128
input_id = X_val[0][0]
attention_mask = X_val[1][0]
token_type_id = X_val[2][0]

print('단어에 대한 정수 인코딩 :',input_id)
print('어텐션 마스크 :',attention_mask)
print('세그먼트 인코딩 :',token_type_id)
print('각 인코딩의 길이 :', len(input_id))
print('정수 인코딩 복원 :',tokenizer.decode(input_id))

In [ ]:
X_test = convert_examples_to_features(test_data['sentence1'], test_data['sentence2'], max_seq_len=max_seq_len, tokenizer=tokenizer)

In [ ]:
train_label = train_data['gold_label'].tolist()
val_label = val_data['gold_label'].tolist()
test_label = test_data['gold_label'].tolist()

In [ ]:
idx_encode = preprocessing.LabelEncoder()
idx_encode.fit(train_label)

y_train = idx_encode.transform(train_label) # 주어진 고유한 정수로 변환
y_val = idx_encode.transform(val_label) # 고유한 정수로 변환
y_test = idx_encode.transform(test_label) # 고유한 정수로 변환

label_idx = dict(zip(list(idx_encode.classes_), idx_encode.transform(list(idx_encode.classes_))))
idx_label = {value: key for key, value in label_idx.items()}
print(label_idx)
print(idx_label)

In [ ]:
class TFBertForSequenceClassification(tf.keras.Model):
    def __init__(self, model_name, num_labels):
        super(TFBertForSequenceClassification, self).__init__()
        self.bert = TFBertModel.from_pretrained(model_name, from_pt=True)
        self.classifier = tf.keras.layers.Dense(num_labels,
                                                kernel_initializer=tf.keras.initializers.TruncatedNormal(0.02),
                                                activation='softmax',
                                                name='classifier')

    def call(self, inputs):
        input_ids, attention_mask, token_type_ids = inputs
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask, token_type_ids=token_type_ids)
        cls_token = outputs[1]
        prediction = self.classifier(cls_token)

        return prediction

In [ ]:
# TPU 작동을 위한 코드 TPU 작동을 위한 코드
resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.config.experimental_connect_to_cluster(resolver)
tf.tpu.experimental.initialize_tpu_system(resolver)
strategy = tf.distribute.experimental.TPUStrategy(resolver)

In [ ]:
with strategy.scope():
  model = TFBertForSequenceClassification("klue/bert-base", num_labels=3)
  optimizer = tf.keras.optimizers.Adam(learning_rate=5e-5)
  loss = tf.keras.losses.SparseCategoricalCrossentropy()
  model.compile(optimizer=optimizer, loss=loss, metrics = ['accuracy'])
  early_stopping = EarlyStopping(
    monitor="val_accuracy", 
    min_delta=0.001,
    patience=2)

  model.fit(
    X_train, y_train, epochs=5, batch_size=32, validation_data = (X_val, y_val),
    callbacks = [early_stopping])

In [ ]:
print("\n 테스트 정확도: %.4f" % (model.evaluate(X_test, y_test, batch_size=1024)[1]))